materia;enunciado;a;b;c;d;e;correta;comentario
Português;Assinale a alternativa em que a concordância verbal está de acordo com a norma-padrão:;Fazem muitos anos que a escola não recebe reformas.;Deve haver muitos alunos interessados na vaga.;Haviam muitos documentos espalhados na secretaria.;Tratam-se de problemas burocráticos difíceis.;Sobrou apenas dois processos antigos.;b;O verbo haver no sentido de existir é impessoal e fica no singular. O verbo fazer indicando tempo também não vai para o plural.
Português;No trecho 'A maioria dos alunos aprovados comemorou', a concordância verbal também poderia ser feita da seguinte forma:;A maioria dos alunos aprovados comemoraram.;A maioria dos alunos aprovados comemorariam.;A maioria dos alunos aprovados comemora.;A maioria dos alunos aprovados comemorasse.;A maioria dos alunos aprovados comemorariam.;a;Com expressões partitivas (a maioria de, grande parte de), o verbo pode concordar com o núcleo (maioria) ou com o especificador (alunos).
Português;Assinale a alternativa em que o uso da crase é OBRIGATÓRIO:;O secretário entregou o documento a ele.;Iremos a Porto Velho amanhã.;Refiro-me à funcionária que fez a matrícula.;As aulas começam a partir de segunda.;Enviei o e-mail a todas as escolas.;c;Feminino determinado (a + a funcionária). Não se usa crase antes de pronome masculino, nomes de cidades sem adjetivo, verbos ou palavras no plural após 'a' no singular.
Português;Qual a função da linguagem predominante em um Ofício ou Memorando?;Fática;Poética;Emotiva;Referencial;Metalinguística;d;A função referencial foca na informação de forma objetiva e direta, essencial na redação oficial.
Português;Assinale a alternativa onde a pontuação está correta:;O aluno, trouxe os documentos hoje.;Ontem, o secretário, protocolou o processo.;Rondônia, é um estado rico em rios.;Os técnicos educacionais, realizaram a reunião.;Brasília, 24 de janeiro de 2026.;e;Não se separa sujeito de predicado por vírgula. A alternativa E mostra a separação correta de local e data.
Português;Indique a frase que apresenta erro de concordância nominal:;As matrículas estão inclusas no sistema.;Seguem anexos os históricos escolares.;É necessário cautela com os prazos.;As certidões seguem em anexo.;Elas mesmas organizaram a sala.;c;O correto seria 'É necessária cautela' (concorda com o substantivo feminino).
Português;Na frase 'Se todos colaborarem, a secretaria funcionará melhor', a oração destacada exprime ideia de:;Causa;Consequência;Condição;Tempo;Finalidade;c;A conjunção 'Se' introduz uma condição para que algo aconteça.
Português;Assinale o sinônimo adequado para a palavra 'CONCISO' na frase: 'O texto oficial deve ser conciso'.;Prolixo;Extenso;Breve;Confuso;Vago;c;Conciso significa algo dito com poucas palavras, de forma breve e direta.
Português;Qual palavra abaixo está grafada INCORRETAMENTE?;Analisar;Exceção;Pretensão;Ascensão;Paralizar;e;O correto é 'Paralisar', pois deriva de 'Paralisia'.
Português;Assinale a alternativa em que o termo sublinhado é um ADVÉRBIO:;O secretário está muito cansado.;Ele trouxe muito papel.;Muitos alunos faltaram.;A escola tem muita história.;Recebemos muitos livros.;a;Aqui 'muito' intensifica o adjetivo 'cansado', sendo um advérbio de intensidade.
