const banco_ro = [
    {
        id: "ro01",
        ano: "2025", banca: "IBADE", orgao: "Prefeitura de Rolim de Moura - RO", prova: "Recepcionista", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Como ocorreu o processo de ocupação das terras rondonienses, considerando a presença de povos indígenas e a chegada dos espanhóis?",
        a: "Os povos indígenas foram os primeiros habitantes da região, mantendo uma relação de harmonia e equilíbrio com a natureza antes da chegada dos espanhóis.",
        b: "Os espanhóis foram os primeiros a explorar a região de Rondônia, mantendo o respeito pela presença dos povos indígenas.",
        c: "A ocupação efetiva de Rondônia teve início apenas no século XX, de forma independente da presença histórica dos povos indígenas ou da influência espanhola.",
        d: "Os espanhóis e os povos indígenas colaboraram de forma pacífica e harmônica para o desenvolvimento da região.",
        e: "A região de Rondônia permaneceu desabitada até a chegada dos portugueses no século XVIII e não dos espanhóis.",
        correta: "a", comentario: "Os povos indígenas são as populações originárias da região. O contato com europeus (espanhóis e depois portugueses) alterou profundamente essa dinâmica original."
    },
    {
        id: "ro02",
        ano: "2025", banca: "IBADE", orgao: "Prefeitura de Rolim de Moura - RO", prova: "Recepcionista", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Rondônia passou por diversas transformações desde a criação do Território Federal do Guaporé até os dias atuais. Sobre esse processo histórico, assinale a alternativa correta.",
        a: "O Território Federal do Guaporé foi criado em 1943 e posteriormente recebeu o nome de Rondônia em homenagem ao Marechal Cândido Rondon.",
        b: "Rondônia se tornou estado brasileiro em 1960, durante o governo de Juscelino Kubitschek, devido ao crescimento da indústria na região.",
        c: "A economia de Rondônia sempre foi baseada na mineração de ouro, sem influência da agricultura e pecuária.",
        d: "A capital de Rondônia já foi transferida várias vezes antes de se estabelecer definitivamente em Ji-Paraná.",
        e: "Desde sua criação, Rondônia sempre teve autonomia política e administrativa, sem interferência do governo federal.",
        correta: "a", comentario: "O Território Federal do Guaporé foi criado pelo Decreto-Lei n.º 5.812 de 1943. Em 1956, o nome foi alterado para Rondônia em homenagem a Cândido Rondon."
    },
    {
        id: "ro03",
        ano: "2025", banca: "IBADE", orgao: "Prefeitura de Rolim de Moura - RO", prova: "Recepcionista", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre o processo de transformação política e economia vivenciado por Rondônia, assinale a alternativa correta.",
        a: "Rondônia sempre foi um estado brasileiro, desde a Proclamação da República em 1889.",
        b: "A economia de Rondônia é baseada exclusivamente na extração de borracha, sem participação de outros setores produtivos.",
        c: "A transformação do território federal de Rondônia em estado ocorreu em 1982, impulsionada pelo crescimento populacional e econômico.",
        d: "O ciclo do ouro foi um dos principais fatores responsáveis pelo desenvolvimento econômico da região durante o século XX.",
        e: "A capital de Rondônia foi transferida diversas vezes ao longo do século XX, até se estabelecer definitivamente em Vilhena.",
        correta: "c", comentario: "Rondônia foi elevada à categoria de Estado pela Lei Complementar nº 41, de 22 de dezembro de 1981, instalada oficialmente em 1982."
    },
    {
        id: "ro04",
        ano: "2025", banca: "IBADE", orgao: "Prefeitura de Rolim de Moura - RO", prova: "Recepcionista", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A economia de Rondônia passou por diversas fases ao longo do tempo. Qual atividade econômica listada abaixo foi importante para o desenvolvimento do estado?",
        a: "Extração de petróleo em larga escala.",
        b: "Exploração de ouro e cassiterita.",
        c: "Extração de gás natural.",
        d: "Indústria automobilística.",
        e: "Produção de vinhos e azeites.",
        correta: "b", comentario: "A mineração de cassiterita e ouro foram ciclos fundamentais para o desenvolvimento econômico e atração migratória em Rondônia."
    },
    {
        id: "ro05",
        ano: "2025", banca: "IBADE", orgao: "Prefeitura de Rolim de Moura - RO", prova: "Fiscal de Regulação - AGERROM", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O INCRA - (Instituto Nacional de Colonização e Reforma Agrária) denominou os pequenos proprietários como colonos, posteriormente chamados de camponeses e, nos anos 1990, de:",
        a: "agricultores familiares.",
        b: "população quilombola.",
        c: "população ribeirinha.",
        d: "beneficiários da reforma agrária.",
        e: "indígenas.",
        correta: "a", comentario: "A partir dos anos 90, o termo 'agricultura familiar' consolidou-se para designar o modelo de produção dos pequenos proprietários rurais."
    },
    {
        id: "ro06",
        ano: "2025", banca: "IBADE", orgao: "Prefeitura de Rolim de Moura - RO", prova: "Agente Administrativo - AGERROM", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Acerca das transformações que ocorrem ao longo da segunda metade do século XX e início do século XXI, no território de Rondônia considere as afirmativas a seguir: I - Expansão do agronegócio; II - Rede urbana com centralidade em Ji-Paraná; III - Movimentos ambientalistas diminuíram a interiorização.",
        a: "Apenas a alternativa I está correta.",
        b: "Apenas as alternativas I e II estão corretas.",
        c: "Apenas a alternativa III está correta.",
        d: "Apenas as alternativas II e III estão corretas.",
        e: "As alternativas I, II e III estão corretas.",
        correta: "b", comentario: "As afirmativas I e II refletem a realidade histórica do estado. A III está incorreta pois a interiorização e a pressão sobre a floresta continuaram intensas."
    },
    {
        id: "ro07",
        ano: "2025", banca: "IBADE", orgao: "Câmara de Rolim de Moura - RO", prova: "Artífice de Copa", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Qual foi o principal motivo da migração de pessoas para o estado de Rondônia nas décadas de 1970 e 1980?",
        a: "A política de ocupação e desenvolvimento da Amazônia, impulsionada pelo governo federal, foi um fator determinante para o crescimento da região.",
        b: "O clima frio e úmido do estado atraiu pessoas em busca de um ambiente mais ameno e agradável.",
        c: "Porque o estado já se consolidava como um grande polo industrial, oferecendo oportunidades de emprego em indústrias.",
        d: "Porque o estado se consolidou como um centro financeiro e bancário, atraindo profissionais especializados do setor de serviços.",
        e: "Devido à descoberta de grandes reservas de petróleo no estado.",
        correta: "a", comentario: "O lema 'integrar para não entregar' do governo militar promoveu a colonização dirigida e a abertura da BR-364."
    },
    {
        id: "ro08",
        ano: "2025", banca: "IBADE", orgao: "Prefeitura de Rolim de Moura - RO", prova: "Agente Administrativo - FCJRM", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Assinale a alternativa que relata os momentos ou ciclos econômicos desde a ocupação até os dias atuais:",
        a: "Construção da Estrada de Ferro Madeira-Mamoré - ciclo da borracha, o “ouro negro” - ciclos da garimpagem de cassiterita e ouro – expansão da “fronteira agrícola” nas terras férteis de Rondônia.",
        b: "Construção da rodovia BR- 364 – ciclo da garimpagem de fosfato, cassiterita e zinco - ciclo da borracha, o “ouro negro” - expansão da “fronteira agrícola” sobre as terras férteis de Rondônia.",
        c: "Conquista das terras indígenas – construção da Estrada de Ferro Madeira-Mamoré - ciclo da garimpagem de zinco, cassiterita e ouro - ciclo da borracha, o “ouro negro”.",
        d: "Construção da Estrada de Ferro Railway Company - conquista das terras indígenas - ciclo da borracha, o “ouro negro” - ciclos da garimpagem de diamante, cassiterita e ouro.",
        e: "Conquista das terras indígenas - ciclo da borracha, o “ouro negro - ciclos da garimpagem de diamante, cassiterita e ouro - construção da rodovia BR- 364 e da Estrada de Ferro Railway Company.",
        correta: "a", comentario: "A sequência correta apresenta os ciclos da borracha/EFMM, seguidos pela mineração (cassiterita/ouro) e a consolidação do agronegócio."
    },
    {
        id: "ro9",
        ano: "2025", banca: "IBADE", orgao: "Prefeitura de Rolim de Moura - RO", prova: "Zeladora - SANEROM", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Qual é o principal reservatório de água de Rondônia, destacado por sua extensão, volume de água e funções essenciais, como abastecimento, geração de energia, transporte e manutenção da biodiversidade?",
        a: "Rio São Francisco.",
        b: "Rio Tiete.",
        c: "Rio Madeira.",
        d: "Rio Paraná.",
        e: "Rio Tocantins.",
        correta: "c", comentario: "O Rio Madeira é o principal curso d'água do estado, fundamental para o transporte (hidrovia) e geração de energia (Usinas de Jirau e Santo Antônio)."
    },
    {
        id: "ro10",
        ano: "2024", banca: "IBADE", orgao: "SESDEC-RO", prova: "Prestador Voluntário", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Desse modo, é considerado o principal minério de Rondônia, ocorrendo com maior frequência nos municípios de Ariquemes, Campo Novo, Itapuã do Oeste, Monte Negro, Porto Velho e Rio Crespo:",
        a: "cassiterita.",
        b: "diamante.",
        c: "zinco.",
        d: "chumbo.",
        e: "ouro.",
        correta: "a", comentario: "A cassiterita (minério de estanho) é historicamente o mineral mais expressivo na economia extrativista mineral de Rondônia."
    },
    {
        id: "ro11",
        ano: "2024", banca: "IBADE", orgao: "SEDUC-RO", prova: "Geral", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A construção da Estrada de Ferro Madeira-Mamoré (EFMM) foi motivada principalmente por qual tratado internacional?",
        a: "Tratado de Tordesilhas",
        b: "Tratado de Madri",
        c: "Tratado de Petrópolis",
        d: "Tratado de Badajós",
        e: "Tratado de Ayacucho",
        correta: "c", comentario: "O Tratado de Petrópolis (1903) formalizou a anexação do Acre ao Brasil, com o compromisso de construir a ferrovia."
    },
    {
        id: "ro12",
        ano: "2024", banca: "IBADE", orgao: "Governo-RO", prova: "Oficial", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Qual é o principal rio que banha a capital, Porto Velho, e abriga importantes usinas hidrelétricas?",
        a: "Rio Guaporé",
        b: "Rio Mamoré",
        c: "Rio Machado",
        d: "Rio Madeira",
        e: "Rio Ji-Paraná",
        correta: "d", comentario: "O Rio Madeira é o principal eixo fluvial e abriga as usinas de Jirau e Santo Antônio."
    },
    {
        id: "ro13",
        ano: "2024", banca: "IBADE", orgao: "Prefeitura", prova: "Técnico", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O Território Federal do Guaporé foi criado em 1943, durante o governo de Getúlio Vargas. Em 1956, seu nome foi alterado em homenagem a:",
        a: "Marechal Rondon",
        b: "Aluízio Ferreira",
        c: "Teodoro Roosevelt",
        d: "Jorge Teixeira",
        e: "Chico Mendes",
        correta: "a", comentario: "Em 1956, o território passou a se chamar Rondônia em homenagem a Cândido Mariano da Silva Rondon."
    },
    {
        id: "ro14",
        ano: "2023", banca: "IBADE", orgao: "Estado-RO", prova: "Educação", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Rondônia faz fronteira internacional com qual país?",
        a: "Peru",
        b: "Bolívia",
        c: "Colômbia",
        d: "Paraguai",
        e: "Venezuela",
        correta: "b", comentario: "O estado de Rondônia possui uma extensa fronteira a oeste e sudoeste com a Bolívia."
    },
    {
        id: "ro15",
        ano: "2023", banca: "IBADE", orgao: "Câmara", prova: "Geral", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Quem foi o primeiro governador do Estado de Rondônia, após sua elevação de território a estado em 1981?",
        a: "Aluízio Ferreira",
        b: "Jorge Teixeira de Oliveira",
        c: "Jerônimo Santana",
        d: "Osvaldo Piana",
        e: "Ivo Cassol",
        correta: "b", comentario: "Coronel Jorge Teixeira foi o último governador do território e o primeiro do estado."
    },
    {
        id: "ro16",
        ano: "2024", banca: "IBADE", orgao: "SEDUC-RO", prova: "Professor", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A economia de Rondônia, a partir da década de 1970, foi impulsionada por qual fenômeno social e econômico?",
        a: "Extração de Petróleo",
        b: "Ciclo da Borracha",
        c: "Projetos de Colonização Agrícola",
        d: "Indústria de Tecnologia",
        e: "Turismo de Neve",
        correta: "c", comentario: "Os projetos do INCRA atraíram milhares de migrantes das regiões Sul e Sudeste para o estado."
    },
    {
        id: "ro17",
        ano: "2024", banca: "IBADE", orgao: "Geral", prova: "Técnico", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Qual rodovia federal é a principal espinha dorsal de Rondônia, ligando Porto Velho a Cuiabá?",
        a: "BR-364",
        b: "BR-230",
        c: "BR-319",
        d: "BR-429",
        e: "BR-101",
        correta: "a", comentario: "A BR-364 é a principal via de escoamento da produção e integração do estado."
    },
    {
        id: "ro18",
        ano: "2023", banca: "IBADE", orgao: "SEDUC", prova: "Administrativo", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre o Forte Príncipe da Beira, assinale a alternativa correta:",
        a: "Foi construído para proteger a fronteira contra incursões francesas.",
        b: "Localiza-se às margens do Rio Guaporé.",
        c: "Foi a primeira capital do território.",
        d: "É uma construção recente do século XX.",
        e: "Foi destruído durante a Guerra do Paraguai.",
        correta: "b", comentario: "O Forte Príncipe da Beira é uma das maiores fortificações portuguesas fora da Europa, no Rio Guaporé."
    },
    {
        id: "ro19",
        ano: "2024", banca: "IBADE", orgao: "Prefeitura", prova: "Oficial", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O bioma predominante no estado de Rondônia é:",
        a: "Cerrado",
        b: "Pantanal",
        c: "Caatinga",
        d: "Amazônico",
        e: "Mata Atlântica",
        correta: "d", comentario: "Rondônia integra a Amazônia Legal e possui a Floresta Amazônica como bioma nativo principal."
    },
    {
        id: "ro20",
        ano: "2024", banca: "IBADE", orgao: "Geral", prova: "Oficial", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O ciclo econômico que trouxe os 'Soldados da Borracha' para a região ocorreu durante:",
        a: "A Primeira Guerra Mundial",
        b: "A Segunda Guerra Mundial",
        c: "O Império de Dom Pedro II",
        d: "A Ditadura Militar",
        e: "O Ciclo do Ouro",
        correta: "b", comentario: "O segundo ciclo da borracha (1942-1945) ocorreu para suprir os aliados na 2ª Guerra Mundial."
    },
    {
        id: "ro21",
        ano: "2023", banca: "IBADE", orgao: "Estado-RO", prova: "Nível Médio", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Qual cidade rondoniense é conhecida como a 'Capital do Café' no estado?",
        a: "Porto Velho",
        b: "Cacoal",
        c: "Vilhena",
        d: "Ariquemes",
        e: "Guajará-Mirim",
        correta: "b", comentario: "Cacoal destaca-se historicamente e economicamente pela produção de café."
    },
    {
        id: "ro22",
        ano: "2024", banca: "IBADE", orgao: "SEDUC-RO", prova: "Geral", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A fundação de Porto Velho está diretamente ligada a qual obra de infraestrutura?",
        a: "Construção da Usina de Samuel",
        b: "Construção da Estrada de Ferro Madeira-Mamoré",
        c: "Pavimentação da Transamazônica",
        d: "Criação do Porto Graneleiro",
        e: "Abertura da BR-364",
        correta: "b", comentario: "Porto Velho surgiu como um ponto de apoio e logística para a construção da ferrovia EFMM."
    },
    {
        id: "ro23",
        ano: "2023", banca: "IBADE", orgao: "Prefeitura", prova: "Saúde", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Rondônia apresenta um clima do tipo:",
        a: "Semiárido",
        b: "Temperado",
        c: "Equatorial Quente e Úmido",
        d: "Subtropical",
        e: "Desértico",
        correta: "c", comentario: "Como estado amazônico, predomina o clima equatorial com altas temperaturas e chuvas abundantes."
    },
    {
        id: "ro24",
        ano: "2024", banca: "IBADE", orgao: "Câmara", prova: "Técnico", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O Marechal Rondon ficou famoso na região por qual atividade principal?",
        a: "Garimpo de ouro",
        b: "Comando de tropas na Revolução Acreana",
        c: "Instalação de linhas telegráficas",
        d: "Governador do Território",
        e: "Construção de hospitais",
        correta: "c", comentario: "A Comissão Rondon instalou linhas telegráficas que integraram o Mato Grosso ao Amazonas."
    },
    {
        id: "ro25",
        ano: "2024", banca: "IBADE", orgao: "Geral", prova: "Superior", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Qual desses municípios localiza-se na região do 'Cone Sul' de Rondônia?",
        a: "Vilhena",
        b: "Ji-Paraná",
        c: "Jaru",
        d: "Ouro Preto do Oeste",
        e: "Machadinho d'Oeste",
        correta: "a", comentario: "Vilhena é a principal cidade da região conhecida como Cone Sul rondoniense."
    },
    {
        id: "ro26",
        ano: "2023", banca: "IBADE", orgao: "SEDUC-RO", prova: "Professor", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A mineração em Rondônia teve um marco histórico com a descoberta de grandes jazidas de qual minério na região de Ariquemes?",
        a: "Ferro",
        b: "Cobre",
        c: "Cassiterita",
        d: "Prata",
        e: "Carvão",
        correta: "c", comentario: "A cassiterita (minério de estanho) foi um grande motor econômico do estado nas décadas de 60 e 70."
    },
    {
        id: "ro27",
        ano: "2024", banca: "IBADE", orgao: "Estado", prova: "Oficial", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A ferrovia Madeira-Mamoré ficou conhecida mundialmente como a 'Ferrovia do Diabo' devido a:",
        a: "Ataques de piratas fluviais",
        b: "Grande número de mortes de trabalhadores por doenças tropicais",
        c: "Suas curvas perigosas nas montanhas",
        d: "Pintura vermelha original das locomotivas",
        e: "Ter sido financiada por bancos estrangeiros falidos",
        correta: "b", comentario: "Milhares de trabalhadores morreram de malária, febre amarela e outras doenças durante a obra."
    },
    {
        id: "ro28",
        ano: "2023", banca: "IBADE", orgao: "Governo", prova: "Técnico", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A Usina Hidrelétrica de Samuel localiza-se no rio:",
        a: "Madeira",
        b: "Jamari",
        c: "Mamoré",
        d: "Guaporé",
        e: "Machado",
        correta: "b", comentario: "Diferente de Jirau e Santo Antônio, a Usina de Samuel fica no Rio Jamari."
    },
    {
        id: "ro29",
        ano: "2024", banca: "IBADE", orgao: "Câmara", prova: "Administrativo", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A cidade de Guajará-Mirim faz fronteira com qual cidade boliviana?",
        a: "Cobija",
        b: "Guayaramerín",
        c: "Santa Cruz de la Sierra",
        d: "La Paz",
        e: "Trinidad",
        correta: "b", comentario: "Guajará-Mirim (Brasil) e Guayaramerín (Bolívia) são cidades gêmeas separadas pelo rio Mamoré."
    },
    {
        id: "ro30",
        ano: "2024", banca: "IBADE", orgao: "Geral", prova: "Geral", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Em termos de divisão regional, Rondônia pertence a qual região brasileira?",
        a: "Centro-Oeste",
        b: "Nordeste",
        c: "Sudeste",
        d: "Norte",
        e: "Sul",
        correta: "d", comentario: "Rondônia é um dos sete estados que compõem a Região Norte do Brasil."
    },
    {
        id: "ro31",
        ano: "2024", banca: "IBADE", orgao: "SESDEC-RO", prova: "Prestador Voluntário", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Assinale a alternativa que indique a Área de Livre Comércio do estado de Rondônia, localizada na divisa com a Bolívia e nas margens do Rio Madeira.",
        a: "Zona Franca de Rondônia.",
        b: "Tabatinga.",
        c: "Guajará-Mirim.",
        d: "Brasiléia.",
        correta: "c", comentario: "A Área de Livre Comércio de Guajará-Mirim (ALCGM) foi criada para promover o desenvolvimento da região fronteiriça."
    },
    {
        id: "ro32",
        ano: "2024", banca: "IBADE", orgao: "SESDEC-RO", prova: "Prestador Voluntário", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Com relação ao relevo, são consideradas as áreas mais elevadas do estado de Rondônia:",
        a: "Serra dos Pacaás Novos e Chapada dos Parecis.",
        b: "Serra do Cachimbo e Serra dos Pacaás.",
        c: "Planalto Rebaixado da Amazônia e Chapada dos Parecis.",
        d: "Serra do Cachimbo e Planalto Rebaixado da Amazônia.",
        correta: "a", comentario: "O ponto culminante de Rondônia está na Serra dos Pacaás Novos (Pico do Tracoá). A Chapada dos Parecis também compõe o relevo de planalto e chapada do estado."
    },
    {
        id: "ro33",
        ano: "2024", banca: "IBADE", orgao: "SESDEC-RO", prova: "Prestador Voluntário", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre o estado de Rondônia, julgue os itens a seguir: I. Localizado ao norte da linha do Equador. II. Porto Velho nas margens do Rio Madeira. III. Localizado na Amazônia Legal. IV. Entre os estados mais antigos da federação.",
        a: "I, II e IV, apenas.",
        b: "II e III, apenas.",
        c: "III e IV, apenas.",
        d: "I e III, apenas.",
        correta: "b", comentario: "Rondônia está ao SUL da linha do Equador e é um dos estados mais NOVOS (1982). Os itens II e III estão corretos."
    },
    {
        id: "ro34",
        ano: "2022", banca: "IBADE", orgao: "Prefeitura de Costa Marques - RO", prova: "Técnico em Radiologia", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O que, para os historiadores, é tida localmente como um dos símbolos da fundação de Rondônia, operando como um mito fundador ou de origem?",
        a: "A construção da rodovia federal que atravessa o estado",
        b: "O destaque de pesquisadores locais",
        c: "O deslocamento de milhares de trabalhadores para a região",
        d: "A questão migratória",
        e: "A construção da Estrada de Ferro Madeira Mamoré",
        correta: "e", comentario: "A EFMM é considerada o marco de nascimento de cidades como Porto Velho e Guajará-Mirim, sendo o principal símbolo histórico do estado."
    },
    {
        id: "ro35",
        ano: "2022", banca: "IBADE", orgao: "Prefeitura de Costa Marques - RO", prova: "Técnico em Radiologia", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Aluízio Pinheiro Ferreira tornou-se, no período de 1943-1946, o:",
        a: "primeiro governador do extinto Território Federal do Guaporé.",
        b: "primeiro prefeito da capital de Rondônia, Porto Velho.",
        c: "primeiro governador do Estado de Rondônia.",
        d: "primeiro governador de Real Forte do Príncipe da Beira.",
        e: "primeiro prefeito da província de pelotões de Guajará-Mirim.",
        correta: "a", comentario: "Aluízio Ferreira foi nomeado por Getúlio Vargas como o primeiro governador do recém-criado Território Federal do Guaporé."
    },
    {
        id: "ro36",
        ano: "2022", banca: "IBADE", orgao: "Prefeitura de Costa Marques - RO", prova: "Microscopista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre o desenvolvimento regional de Rondônia, julgue os itens sobre migrantes e impactos ambientais.",
        a: "I, III e IV.",
        b: "I, IV e V.",
        c: "II e IV.",
        d: "II e III.",
        e: "I, II e III.",
        correta: "a", comentario: "O item II está incorreto pois o licenciamento ambiental não anula o impacto ambiental, apenas o regula. Os demais descrevem corretamente a dinâmica de ocupação e sustentabilidade."
    },
    {
        id: "ro37",
        ano: "2022", banca: "IBADE", orgao: "Prefeitura de Costa Marques - RO", prova: "Microscopista", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre o Território Federal do Guaporé, é INCORRETO afirmar que:",
        a: "nasceu composto por terras de Mato Grosso e Amazonas.",
        b: "foi criado no governo de Getúlio Vargas.",
        c: "o primeiro Governador foi o Coronel Aluísio Pinheiro Ferreira.",
        d: "no governo Juscelino Kubitschek, passou a se chamar Rondônia.",
        e: "foi criado no Regime Militar e tinha como finalidade conter a imigração.",
        correta: "e", comentario: "O Território foi criado em 1943 (Era Vargas) e não no Regime Militar. Além disso, a finalidade era integrar a região e não conter a imigração."
    },
    {
        id: "ro38",
        ano: "2022", banca: "IBADE", orgao: "Prefeitura de Costa Marques - RO", prova: "Microscopista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre a exploração da atividade agrícola em Rondônia iniciada nos anos 70, é correto afirmar:",
        a: "a implantação da hidrovia do rio Madeira é um importante meio de escoamento da produção de grãos.",
        b: "o mal planejamento da rodovia BR–364 criou um isolamento geográfico.",
        c: "Getúlio Vargas utilizou o Território para colocar em prática o PIN.",
        d: "em 2003, Rondônia não pôde ser declarado livre de febre aftosa.",
        e: "nos dias atuais, Rondônia possui o maior rebanho bovino do Brasil.",
        correta: "a", comentario: "A Hidrovia do Madeira é vital para o escoamento de soja. A BR-364 integrou o estado (não isolou) e o PIN é da década de 70 (Ditadura), não de Vargas."
    },
    {
        id: "ro39",
        ano: "2022", banca: "IBADE", orgao: "Prefeitura de Costa Marques - RO", prova: "Microscopista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre o município de Costa Marques, julgue as assertivas de I a V.",
        a: "I, II e IV.",
        b: "II, III e IV.",
        c: "I, IV e V.",
        d: "II e IV.",
        e: "III e V.",
        correta: "a", comentario: "O Forte fica na margem DIREITA do Rio Guaporé (III incorreta) e São Francisco do Guaporé é município autônomo (V incorreta)."
    },
    {
        id: "ro40",
        ano: "2022", banca: "IBADE", orgao: "Prefeitura de Costa Marques - RO", prova: "Microscopista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Com base no contingente populacional de Rondônia e Porto Velho, assinale a correta:",
        a: "Costa Marques é um dos dez maiores municípios.",
        b: "PPP é documento escolar apenas de professores.",
        c: "A população da capital Porto Velho representa cerca de 30% dos moradores do estado.",
        d: "Rondônia tem a maior população da Região Norte.",
        e: "Rondônia é um estado com alta densidade demográfica.",
        correta: "c", comentario: "Porto Velho concentra quase um terço da população estadual. O Amazonas e o Pará possuem populações maiores que Rondônia na Região Norte."
    },
    {
        id: "ro41",
        ano: "2020", banca: "IBADE", orgao: "Prefeitura de Ministro Andreazza - RO", prova: "Zelador", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Em Ministro Andreazza, quem comanda o Município como Chefe do Poder Executivo é o:",
        a: "presidente da república.",
        b: "governador.",
        c: "prefeito.",
        d: "senador.",
        e: "comandante das forças armadas.",
        correta: "c", comentario: "O chefe do Poder Executivo Municipal é sempre o Prefeito."
    },
    {
        id: "ro42",
        ano: "2020", banca: "IBADE", orgao: "Prefeitura de Ministro Andreazza - RO", prova: "Zelador", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre a economia de Rondônia, verifica-se nos últimos anos uma expansão da produção de:",
        a: "soja.",
        b: "cassiterita.",
        c: "maçã.",
        d: "prata.",
        e: "minério de ferro.",
        correta: "a", comentario: "A soja é o principal produto agrícola de exportação e está em constante expansão no estado."
    },
    {
        id: "ro43",
        ano: "2020", banca: "IBADE", orgao: "Prefeitura de Ministro Andreazza - RO", prova: "Zelador", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O Município de Ministro Andreazza localiza-se na região brasileira denominada:",
        a: "Nordeste.",
        b: "Sul.",
        c: "Norte.",
        d: "Sudeste.",
        e: "Centro-Oeste.",
        correta: "c", comentario: "Rondônia integra a Região Norte do Brasil."
    },
    {
        id: "ro44",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Motorista", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O município de Ji-Paraná tem hoje o maior parque de exposição do norte e o segundo maior do Brasil. Anualmente, é realizado um evento que já reuniu um público próximo a 300 mil pessoas. Trata-se da:",
        a: "EXPOINEL ( Exposição Internacional de Gado Zebu ).",
        b: "EXPOJIPA (Exposição Agropecuária e Industrial de Ji-Paraná).",
        c: "EXPOLONDRINA ( Exposição Agropecuária e Industrial de Londrina).",
        d: "AGRISHOW ( Exposição de Produtos Agrícolas de Ji-Paraná)",
        e: "EXPOAGRO (Exposição de Produtos Agrícolas e Gado de Rondônia).",
        correta: "b", comentario: "A EXPOJIPA é o evento mais tradicional de Ji-Paraná, realizado no Parque de Exposições Hermínio Victorelli."
    },
    {
        id: "ro45",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Motorista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A respeito da hidrografia de Ji-Paraná, pode-se afirmar que:",
        a: "não há trecho navegável.",
        b: "o rio Urupá deságua no rio Amazonas.",
        c: "o rio Machado deságua no rio Negro.",
        d: "o principal e maior rio é o rio Mamoré.",
        e: "os dois principais e maiores rios são o Urupá e o Machado.",
        correta: "e", comentario: "Ji-Paraná é conhecida como a 'Cidade Coração de Rondônia' e é marcada pelo encontro dos rios Urupá e Machado."
    },
    {
        id: "ro46",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Motorista", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Em 11 de outubro de 1977, o então presidente da República concedeu emancipação política à Vila de Rondônia. O termos que completam o texto corretamente são:",
        a: "Humberto Castelo Branco / à Comarca de Abunã.",
        b: "Ernesto Geisel / à Comarca de Porto Velho.",
        c: "Ranieri Mazzilli / ao território de Rondônia.",
        d: "Artur da Costa e Silva / ao estado do Mato Grosso.",
        e: "João Figueiredo / ao estado de Mato Grosso.",
        correta: "b", comentario: "O Presidente Ernesto Geisel assinou a Lei nº 6.448/77. Na época da criação, o município ainda integrava a Comarca de Porto Velho para fins judiciais."
    },
    {
        id: "ro47",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Motorista", materia: "Legislação Local",
        assunto: "Hist e Geo RO",
        enunciado: "De acordo com a Lei de Licenciamento Ambiental nº 2807/2015, a autorização que permite extrair bem mineral por tempo não superior a 20 anos denomina-se:",
        a: "Licença Municipal de Extração Mineral.",
        b: "Viabilidade Ambiental.",
        c: "Licença Municipal de Instalação (LMI).",
        d: "Licença Municipal de Operação (LMO).",
        e: "Licença de Operação de Regularização (LOR).",
        correta: "a", comentario: "A Licença Municipal de Extração Mineral é o instrumento específico para a atividade extrativista regulada pela prefeitura."
    },
    {
        id: "ro48",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Motorista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Rondônia tem uma população estimada em 1.800.000 habitantes. Acerca do assunto, pode-se afirmar que:",
        a: "a maior parte da população vive nas cidades.",
        b: "a maior parte da população vive na área rural.",
        c: "a cidade mais populosa é Vilhena.",
        d: "a cidade menos populosa é Parecis.",
        e: "Ji-Paraná e Ariquemes têm, quantitativamente, a mesma população que Porto Velho.",
        correta: "a", comentario: "Rondônia possui um alto índice de urbanização, com a maior concentração populacional nas zonas urbanas, especialmente em Porto Velho e Ji-Paraná."
    },
    {
        id: "ro49",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Motorista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Rondônia faz fronteira a leste com o(a):",
        a: "Estado do Amazonas.",
        b: "Estado do Acre.",
        c: "República da Bolívia.",
        d: "Estado do Mato Grosso.",
        e: "República do Peru.",
        correta: "d", comentario: "A fronteira leste de Rondônia é compartilhada com o estado do Mato Grosso."
    },
    {
        id: "ro50",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Motorista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Rio que nasce nos Andes bolivianos e forma o rio Madeira ao encontrar o rio Beni. Trata-se do rio:",
        a: "Aponiã.",
        b: "Ouro Fino.",
        c: "Machado.",
        d: "Mamoré.",
        e: "Negro.",
        correta: "d", comentario: "O Rio Mamoré é fundamental para a delimitação da fronteira Brasil-Bolívia e formador do Madeira."
    },
    {
        id: "ro51",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Motorista", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O Território Federal do Guaporé foi criado em 1943 através do Decreto nº 5.812, assinado pelo então Presidente:",
        a: "Artur Bernardes.",
        b: "José Linhares.",
        c: "Eurico Gaspar Dutra.",
        d: "Getúlio Vargas.",
        e: "Café Filho.",
        correta: "d", comentario: "Getúlio Vargas criou o território em 13 de setembro de 1943, retirando áreas do Amazonas e Mato Grosso."
    },
    {
        id: "ro52",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Motorista", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Povo indígena que ocupa reserva de 160.000 ha nos Igarapés Lourdes e mantém contato com Ji-Paraná:",
        a: "Gaviões.",
        b: "Suruis.",
        c: "Pakaás Novos.",
        d: "Cinta Larga.",
        e: "Araras.",
        correta: "a", comentario: "Os Gaviões (Ikolen) habitam a TI Igarapé Lourdes, localizada em Ji-Paraná, e possuem forte interação com a cidade."
    },
    {
        id: "ro53",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Técnico de Informática", materia: "Legislação Local",
        assunto: "Hist e Geo RO",
        enunciado: "De acordo com o Código Ambiental de Ji-Paraná, Lei nº 1113/2001, o conceito ligado à promoção de condições ambientais favoráveis à saúde é:",
        a: "recursos ambientais.",
        b: "gestão ambiental.",
        c: "salubridade ambiental.",
        d: "fragmentos florestais.",
        e: "ecossistema.",
        correta: "c", comentario: "A salubridade ambiental é o estado que previne doenças e garante o bem-estar através do equilíbrio do meio."
    },
    {
        id: "ro54",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Técnico de Informática", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Na composição econômica de Ji-Paraná, pequenas plantações vendidas para proprietários maiores são transformadas em grande parte em:",
        a: "pastos.",
        b: "área de extrativismo vegetal.",
        c: "área de extrativismo mineral.",
        d: "área de turismo ecológico.",
        e: "assentamentos rurais.",
        correta: "a", comentario: "O processo de concentração de terras em Rondônia frequentemente substitui a agricultura familiar por pastagens para pecuária de corte."
    },
    {
        id: "ro55",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Técnico de Informática", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O clima predominante no município de Ji-Paraná é o:",
        a: "tropical atlântico.",
        b: "tropical de altitude.",
        c: "subtropical.",
        d: "semiárido.",
        e: "tropical úmido.",
        correta: "e", comentario: "O clima de Rondônia é predominantemente Equatorial/Tropical úmido, caracterizado por altas temperaturas e elevado índice pluviométrico."
    },
    {
        id: "ro56",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Técnico de Informática", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Destino histórico em Ji-Paraná que possui acervo sobre telégrafos, artesanato indígena e artefatos de pedra:",
        a: "Museu do Homem do Norte.",
        b: "Museu do Seringal.",
        c: "Museu do Índio.",
        d: "Museu das Comunicações.",
        e: "Fundação Cultural de Rondônia.",
        correta: "d", comentario: "O Museu das Comunicações Marechal Rondon, em Ji-Paraná, preserva a história da Comissão Rondon e das linhas telegráficas na região."
    },
    {
        id: "ro57",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Técnico de Informática", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "São consideradas as principais atividades do extrativismo vegetal no estado de Rondônia:",
        a: "a produção de café e da mandioca.",
        b: "a produção do café e do cacau.",
        c: "a exploração do ouro e da cassiterita.",
        d: "a exploração de madeira e da borracha.",
        e: "a exploração do nióbio e da cassiterita.",
        correta: "d", comentario: "Café e cacau são agricultura; ouro e cassiterita são extrativismo mineral. Madeira e borracha são os pilares históricos e atuais do extrativismo vegetal."
    },
    {
        id: "ro58",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Técnico de Informática", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O Primeiro Ciclo da Borracha começou a decair a partir de 1912, principalmente pela:",
        a: "falta do produto (matéria-prima).",
        b: "concorrência com os preços do látex americano.",
        c: "preço praticado no continente asiático, especialmente na Malásia.",
        d: "concorrência com os preços do látex boliviano.",
        e: "preço praticado no continente africano, especialmente no Congo.",
        correta: "c", comentario: "A concorrência das plantações organizadas (seringais de cultivo) na Ásia, iniciada por sementes contrabandeadas da Amazônia, derrubou os preços internacionais."
    },
    {
        id: "ro59",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Técnico de Informática", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O estado de Rondônia faz limite com a República da Bolívia ao/a:",
        a: "Norte e Nordeste.",
        b: "Sul.",
        c: "Sul e sudeste.",
        d: "Sudeste.",
        e: "Noroeste.",
        correta: "b", comentario: "A fronteira internacional de Rondônia com a Bolívia localiza-se ao Sul e a Oeste do estado."
    },
    {
        id: "ro60",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Técnico de Informática", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A aldeia Lapetanha, do povo Paiter Suruí (vencedores no Concafé), localiza-se próxima à cidade de:",
        a: "Guajará-Mirim.",
        b: "Cacoal.",
        c: "Rolim de Moura.",
        d: "Jaru.",
        e: "Seringueiras.",
        correta: "b", comentario: "A Terra Indígena Sete de Setembro, onde vivem os Paiter Suruí, fica na região de Cacoal, polo da cafeicultura rondoniense."
    },
    {
        id: "ro61",
        ano: "2020", banca: "IBADE", orgao: "Câmara de Ji-Paraná - RO", prova: "Técnico de Informática", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Acerca dos afluentes formadores do rio Machado (Comemoração e Apediá), pode-se afirmar que:",
        a: "suas nascentes estão na região norte de Rondônia.",
        b: "o rio Machado tem a foz no rio Madeira, na região sul.",
        c: "têm suas nascentes na Chapada dos Parecis, no município de Vilhena.",
        d: "têm suas nascentes na Planície Amazônica, em Rolim de Moura.",
        e: "suas nascentes estão no município de Cacoal.",
        correta: "c", comentario: "O Rio Machado (ou Ji-Paraná) nasce na Chapada dos Parecis, no Cone Sul (Vilhena/Pimenta Bueno), correndo para o norte até desaguar no Rio Madeira."
    },
    {
        id: "ro62",
        ano: "2020", banca: "IBADE", orgao: "Prefeitura de Ministro Andreazza - RO", prova: "Técnico Eletricista", materia: "Atualidades de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Equipamentos adquiridos pelo Governo em 2020 fundamentais para fiscalização do desmatamento e incêndios em áreas de difícil acesso:",
        a: "separadores de óleo.",
        b: "aviões concorde.",
        c: "agrotóxicos.",
        d: "guindastes.",
        e: "drones.",
        correta: "e", comentario: "O uso de drones (VANTs) tornou-se essencial para o monitoramento ambiental remoto e combate a crimes ambientais em Rondônia."
    },
    {
        id: "ro63",
        ano: "2020", banca: "IBADE", orgao: "Prefeitura de Santa Luzia D'Oeste - RO", prova: "Assistente de Controle Interno", materia: "Atualidades de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Qual argumento a SEDUC-RO apresentou em 2020 para propor (embora não efetivada) a retirada de clássicos literários das escolas?",
        a: "Que os livros eram demasiadamente ultrapassados.",
        b: "Que não haviam passado por revisão criteriosa.",
        c: "Apresentavam altos custos de manutenção.",
        d: "Que os livros apresentavam conteúdos inadequados às crianças e adolescentes.",
        e: "Que houve superfaturamento.",
        correta: "d", comentario: "O memorando da época alegava que as obras continham conteúdos 'inadequados' para a faixa etária escolar, gerando grande polêmica nacional."
    },
    {
        id: "ro64",
        ano: "2020", banca: "IBADE", orgao: "Prefeitura de Santa Luzia D'Oeste - RO", prova: "Artifice de Pedreiro", materia: "Atualidades de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O que motivou a greve dos motoristas e cobradores de ônibus em Porto Velho em janeiro de 2020?",
        a: "Atrasos nos salários e benefícios dos trabalhadores.",
        b: "Insegurança causada pelo aumento de assaltos.",
        c: "Reivindicações por reajuste salarial.",
        d: "Superlotação dos ônibus.",
        e: "Reinvindicação de participação nos lucros.",
        correta: "a", comentario: "A greve foi motivada pelo descumprimento de obrigações trabalhistas e atrasos nos pagamentos por parte das empresas concessionárias."
    },
    {
        id: "ro65",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Porto Velho - RO", prova: "Professor", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Depois da segunda época da borracha, a economia do estado foi marcada pela:",
        a: "“Belle Époque Amazônica”.",
        b: "era do telégrafo.",
        c: "exploração extrativista, pelo garimpo de ouro, cassiterita e diamantes.",
        d: "produção de algodão.",
        e: "cultura do café.",
        correta: "c", comentario: "Com o fim do Segundo Ciclo da Borracha (Soldados da Borracha), o novo fôlego econômico veio com o ciclo da mineração (especialmente cassiterita nos anos 50/60)."
    },
    {
        id: "ro66",
        ano: "2019", banca: "IBADE", orgao: "SAAE de Vilhena - RO", prova: "Agente Administrativo", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Bacia hidrográfica formada pela confluência dos rios Mamoré e Beni, onde se localizam as usinas de Santo Antônio e Jirau:",
        a: "Madeira.",
        b: "Amazonas.",
        c: "Machado.",
        d: "Jamari.",
        e: "Abunã.",
        correta: "a", comentario: "O Rio Madeira nasce do encontro dos rios Mamoré e Beni e abriga o Complexo Hidrelétrico do Madeira."
    },
    {
        id: "ro67",
        ano: "2019", banca: "IBADE", orgao: "SAAE de Vilhena - RO", prova: "Agente Administrativo", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Assinale a alternativa que descreve corretamente os limites de Rondônia:",
        a: "ao norte com Mato Grosso...",
        b: "ao norte com o estado do Amazonas, a leste e sudeste com o estado do Mato Grosso, a sudeste e oeste com a Bolívia e a nordeste com os estados do Amazonas e Acre.",
        c: "ao norte com o estado do Acre...",
        d: "ao norte com a Bolívia...",
        e: "ao norte com o estado do Acre...",
        correta: "b", comentario: "Rondônia limita-se ao Norte com Amazonas, Leste/Sudeste com Mato Grosso, Sul/Oeste com Bolívia e Noroeste com Acre."
    },
    {
        id: "ro68",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Seringueiras - RO", prova: "Almoxarife", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O forte situado em Costa Marques, candidato a patrimônio mundial da Unesco, é o:",
        a: "Forte Orange.",
        b: "Forte São Marcelo.",
        c: "Forte Príncipe da Beira.",
        d: "Fortaleza de Santa Cruz da Barra.",
        e: "Forte Tamandaré.",
        correta: "c", comentario: "O Real Forte Príncipe da Beira é a maior edificação militar portuguesa construída fora da Europa no período colonial."
    },
    {
        id: "ro69",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Seringueiras - RO", prova: "Almoxarife", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "De acordo com dados demográficos de Seringueiras (Censo 2015), a característica da população é:",
        a: "a maior parte habitantes da região urbana.",
        b: "38% desses habitantes pertencendo à população urbana.",
        c: "a menor parte habitantes da região rural.",
        d: "90% desses habitantes pertencendo à população rural.",
        e: "distribuída equilibradamente.",
        correta: "b", comentario: "Seringueiras é um caso atípico em Rondônia onde a maioria da população ainda reside na zona rural (mais de 60%)."
    },
    {
        id: "ro70",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Seringueiras - RO", prova: "Almoxarife", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O gentílico de quem nasce em Seringueiras é:",
        a: "rondoniense.",
        b: "nortista.",
        c: "nordestino.",
        d: "seringueiro.",
        e: "seringueinense.",
        correta: "e", comentario: "Embora o nome remeta ao 'seringueiro' (profissão), o gentílico oficial do município é seringueinense."
    },
    {
        id: "ro71",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Seringueiras - RO", prova: "Almoxarife", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O município de Seringueiras foi desmembrado dos municípios de:",
        a: "Porto Velho e Ji-Paraná.",
        b: "Alto Paraíso e Costa Marques.",
        c: "Cerejeiras e Colorado do Oeste.",
        d: "São Miguel do Guaporé e Costa Marques.",
        e: "Governador Jorge Teixeira e Cerejeiras.",
        correta: "d", comentario: "Seringueiras originou-se de áreas que pertenciam a São Miguel do Guaporé e Costa Marques, ao longo da BR-429."
    },
    {
        id: "ro72",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Seringueiras - RO", prova: "Agente Administrativo", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Seringueiras – RO foi elevado à categoria de município pela Lei Estadual nº 370, de 13-02-1992. Foi desmembrado dos municípios de:",
        a: "São Miguel do Guaporé e Costa Marques.",
        b: "Rolin de Moura e São Francisco do Guaporé.",
        c: "Rolin de Moura e Rodrigues Alves.",
        d: "São Miguel do Guaporé – Urupá.",
        e: "Costa Marques – Urupá.",
        correta: "a", comentario: "Seringueiras originou-se do NUAR Bom Princípio, com terras retiradas de São Miguel e Costa Marques."
    },
    {
        id: "ro73",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Vilhena - RO", prova: "Arquiteto", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Assinale a alternativa que descreve corretamente o contexto econômico e político do Território Federal de Rondônia entre as décadas de 1960 e 1970.",
        a: "Início do chamado Ciclo da Borracha e chegada de nordestinos.",
        b: "Auge da extração da borracha e construção da EFMM.",
        c: "Implantação dos Projetos Integrados de Colonização e proibição da lavra manual de cassiterita.",
        d: "Abertura da hidrovia do rio Madeira e homenagem ao Marechal Rondon.",
        e: "Início da exploração de cassiterita em Ariquemes e expansão da fronteira agrícola.",
        correta: "e", comentario: "Este período foi marcado pela descoberta da cassiterita em Ariquemes (1958), a abertura da BR-364 e a colonização dirigida pelo INCRA (anos 70)."
    },
    {
        id: "ro74",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Vilhena - RO", prova: "Arquiteto", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre o processo de criação do Território Federal do Guaporé (1943), é correto afirmar que:",
        a: "foi criado a partir do desmembramento de parte do Mato Grosso e Amazonas, sendo inicialmente formado por quatro municípios.",
        b: "foi uma forma de diminuir o poder político das elites matogrossenses.",
        c: "ocorreu após pressão internacional pela presença de alemães na II Guerra.",
        d: "visava instalar indústrias no vale do Guaporé.",
        e: "conflitos com bolivianos exigiram presença militar.",
        correta: "a", comentario: "O território foi criado pelo Decreto-Lei 5.812 com terras de MT e AM. Os municípios iniciais eram Porto Velho e Guajará-Mirim (desmembrados de AM) e Santo Antônio do Rio Madeira e Mato Grosso (desmembrados de MT)."
    },
    {
        id: "ro75",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Vilhena - RO", prova: "Arquiteto", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Com cerca de 3.300 quilômetros de extensão, o Rio Madeira é um dos principais afluentes do Amazonas. Sobre ele, assinale a correta:",
        a: "Não apresenta diferenças de coloração nas águas.",
        b: "Não possui hidrelétricas devido à variação do volume.",
        c: "Sua bacia abarca territórios de Brasil, Bolívia, Peru e Equador.",
        d: "Surge do encontro dos rios Mamoré e Beni, com nascentes nos Andes.",
        e: "Atravessa duas capitais estaduais: Manaus e Porto Velho.",
        correta: "d", comentario: "O Madeira é um rio de 'águas brancas' (barrentas) formado pelo Mamoré e Beni. Manaus fica no Rio Negro, não no Madeira."
    },
    {
        id: "ro76",
        ano: "2019", banca: "IBADE", orgao: "Prefeitura de Vilhena - RO", prova: "Arquiteto", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O Real Forte Príncipe da Beira (Séc. XVIII) é patrimônio nacional. Qual foi o principal motivo de sua construção?",
        a: "Preocupação com bandeirantes paulistas.",
        b: "Assegurar a posse dos territórios do rio Guaporé ante a indefinição de fronteiras entre Portugal e Espanha.",
        c: "Defender o território de ataques franceses e Tucujus.",
        d: "Proteger operários da EFMM.",
        e: "Estimular o escoamento da produção de borracha.",
        correta: "b", comentario: "O forte foi erguido para consolidar o Tratado de Madri e defender a fronteira oeste da colônia portuguesa contra os espanhóis."
    },
    {
        id: "ro77",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Porto Velho - RO", prova: "Tradutor de Libras", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A agropecuária responde por 20% do PIB de Rondônia. Qual o principal produto de exportação?",
        a: "carne suína.",
        b: "carne bovina.",
        c: "mandioca.",
        d: "soja.",
        e: "produção de orgânicos.",
        correta: "d", comentario: "Embora a carne bovina seja fortíssima, a soja consolidou-se como o principal item da pauta de exportações em valor."
    },
    {
        id: "ro78",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Porto Velho - RO", prova: "Tradutor de Libras", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O Território Federal de Guaporé (1943) foi constituído mediante o desmembramento das áreas:",
        a: "da Bolívia e do Peru.",
        b: "da Bolívia e do Mato Grosso.",
        c: "do Mato Grosso e do Acre.",
        d: "do Mato Grosso e do Amazonas.",
        e: "do Amazonas e da Bolívia.",
        correta: "d", comentario: "Questão clássica: o território nasceu da junção de terras cedidas por Mato Grosso e Amazonas."
    },
    {
        id: "ro79",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Porto Velho - RO", prova: "Tradutor de Libras", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Assinale a alternativa que indica corretamente os limites geográficos de Rondônia:",
        a: "Amazonas(leste), Bolívia(sul), Acre(oeste), Mato grosso(sul e oeste).",
        b: "Amazonas(sul), Bolívia(oeste), Acre(leste), Mato Grosso (norte e nordeste).",
        c: "Amazonas(sul), Bolívia(leste), Acre( oeste),Mato grosso( noroeste e norte).",
        d: "Amazonas (norte), Bolívia (sul), Acre (oeste), Mato Grosso (leste).",
        e: "Amazonas(nordeste), Bolívia (sul e sudeste), Acre( leste), Mato Grosso(norte).",
        correta: "d", comentario: "Norte: Amazonas; Sul: Bolívia; Oeste: Acre/Bolívia; Leste: Mato Grosso."
    },
    {
        id: "ro80",
        ano: "2018", banca: "IBADE", orgao: "Prefeitura de Ji-Paraná - RO", prova: "Merendeira", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O rio Ji-Paraná (rio Machado) possui sua nascente na seguinte região:",
        a: "Chapada dos Parecis.",
        b: "Chapada dos Veadeiros.",
        c: "Serra dos Carajás.",
        d: "Serra Pacaraima.",
        e: "Serra do Divisor.",
        correta: "a", comentario: "O Rio Machado nasce na Chapada dos Parecis, no sul do estado."
    },
    {
        id: "ro81",
        ano: "2018", banca: "IBADE", orgao: "Prefeitura de Ji-Paraná - RO", prova: "Merendeira", materia: "Conhecimentos Gerais",
        assunto: "Hist e Geo RO",
        enunciado: "O município de Ji-Paraná, nas últimas eleições (referência 2018), empossou a seguinte quantidade de vereadores:",
        a: "62.",
        b: "8.",
        c: "17.",
        d: "31.",
        e: "49.",
        correta: "c", comentario: "Conforme a legislação municipal baseada na população, Ji-Paraná possui 17 cadeiras na Câmara Municipal."
    },
    {
        id: "ro82",
        ano: "2018", banca: "IBADE", orgao: "Prefeitura de Ji-Paraná - RO", prova: "Merendeira", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Em Ji-Paraná, qual das lavouras a seguir apresentou a maior área plantada (dados de 2017/2018)?",
        a: "Mamão",
        b: "Café",
        c: "Limão",
        d: "Amendoim",
        e: "Goiaba",
        correta: "b", comentario: "O café é a cultura perene de maior expressão histórica e territorial em Ji-Paraná."
    },
    {
        id: "ro83",
        ano: "2018", banca: "IBADE", orgao: "Prefeitura de Ji-Paraná - RO", prova: "Merendeira", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O dia da criação do município de Ji-Paraná, feriado municipal, é:",
        a: "22 de novembro.",
        b: "23 de junho.",
        c: "20 de fevereiro.",
        d: "02 de abril.",
        e: "16 de agosto.",
        correta: "a", comentario: "Ji-Paraná foi instalada em 22 de novembro de 1977."
    },
    {
        id: "ro84",
        ano: "2018", banca: "IBADE", orgao: "Prefeitura de Ji-Paraná - RO", prova: "Merendeira", materia: "Conhecimentos Gerais",
        assunto: "Hist e Geo RO",
        enunciado: "Nas eleições de 2016 em Ji-Paraná, quem foi eleito como vice-prefeito?",
        a: "Marcito Aparecido Pinto",
        b: "Cláudia de Jesus",
        c: "Jesualdo Pires",
        d: "Ademilson Procópio Anastácio",
        e: "Affonso Cândido",
        correta: "a", comentario: "Marcito Pinto foi vice de Jesualdo Pires e posteriormente assumiu a prefeitura."
    },
    {
        id: "ro85",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Motorista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre os municípios a seguir, assinale a alternativa que indica o município localizado mais distante do município de Cacoal.",
        a: "Pimenta Bueno",
        b: "Rolim de Moura",
        c: "Nova Mamoré",
        d: "Castanheiras",
        e: "Vilhena",
        correta: "c", comentario: "Nova Mamoré fica na região de fronteira ao norte/oeste, próximo a Guajará-Mirim, sendo consideravelmente mais distante de Cacoal do que os municípios do Cone Sul ou da região central."
    },
    {
        id: "ro86",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Motorista", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O nome da capital de Rondônia é em função a um porto localizado às margens de um importante rio que passa pelo estado. O nome do rio que corta a cidade de Porto Velho é:",
        a: "Roosevelt.",
        b: "Paucerne.",
        c: "Corumbiara",
        d: "Amazonas.",
        e: "Madeira.",
        correta: "e", comentario: "Porto Velho foi fundada às margens do Rio Madeira durante a construção da Estrada de Ferro Madeira-Mamoré."
    },
    {
        id: "ro87",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Agente de Manutenção", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Rondônia foi elevado à categoria de estado na década de 80 do século XX. Antes disso, o que hoje é o estado de Rondônia era denominado:",
        a: "Estado de Ji-Paraná.",
        b: "Território Federal de Rondônia.",
        c: "Estado do Amazonas do Sul.",
        d: "Território de Porto Velho.",
        e: "Estado do Oeste Brasileiro.",
        correta: "b", comentario: "Rondônia foi Território Federal de 1943 até 1981, quando a Lei Complementar nº 41 criou o Estado de Rondônia."
    },
    {
        id: "ro88",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Agente de Manutenção", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre as alternativas a seguir, assinale a que indica o político que exerceu o cargo de governador de Rondônia mais recentemente (em relação a 2018).",
        a: "Assis Canuto",
        b: "Osvaldo Piana",
        c: "Jorge Teixeira",
        d: "Teodorico Gaíva",
        e: "João Aparecido Cahulla",
        correta: "e", comentario: "João Cahulla foi governador em 2010. Os outros nomes citados são de períodos anteriores (Jorge Teixeira foi o último do território e primeiro do estado)."
    },
    {
        id: "ro89",
        ano: "2018", banca: "IBADE", orgao: "Prefeitura de Ji-Paraná - RO", prova: "Técnico de Saúde Bucal", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre os municípios a seguir, assinale o que possui limites com o município de Ji-Paraná.",
        a: "Buriti",
        b: "Rio Crespo",
        c: "São Francisco",
        d: "Rolim de Moura",
        e: "Ouro Preto do Oeste",
        correta: "e", comentario: "Ouro Preto do Oeste é vizinho imediato de Ji-Paraná pela BR-364."
    },
    {
        id: "ro90",
        ano: "2018", banca: "IBADE", orgao: "Prefeitura de Ji-Paraná - RO", prova: "Artesão", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Anterior a denominação de Território Federal de Rondônia (1956), o atual estado era denominado de Território Federal do:",
        a: "Jaru.",
        b: "Mamoré.",
        c: "Guaporé.",
        d: "Porto Velho.",
        e: "Guajará-Mirim.",
        correta: "c", comentario: "Criado em 1943 como Território Federal do Guaporé, teve seu nome alterado em 1956 para Rondônia em homenagem a Rondon."
    },
    {
        id: "ro91",
        ano: "2018", banca: "IBADE", orgao: "Prefeitura de Ji-Paraná - RO", prova: "Artesão", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre as unidades de relevo a seguir, assinale a alternativa que indica uma unidade existente no estado de Rondônia.",
        a: "Depressão do Miranda",
        b: "Depressão do Araguaia",
        c: "Planaltos Residuais Sul-Amazônicos",
        d: "Planaltos e Chapadas da Bacia do Parnaíba",
        e: "Depressão Periférica da Borda Leste da Bacia do Paraná",
        correta: "c", comentario: "Segundo a classificação de Jurandyr Ross, o relevo de RO é composto por Depressões Amazônicas e Planaltos Residuais Sul-Amazônicos."
    },
    {
        id: "ro92",
        ano: "2018", banca: "IBADE", orgao: "Prefeitura de Ji-Paraná - RO", prova: "Artesão", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Assinale a alternativa que apresenta o fator mais importante no processo de ocupação de Rondônia, a partir da segunda metade do século XX.",
        a: "Construção da rodovia BR-364",
        b: "Idealização da ferrovia Madeira-Mamoré",
        c: "Estabelecimentos das linhas telegráficas",
        d: "Expedição colonizadora de Cândido Rondon",
        e: "Guerra entre o Brasil e o Paraguai",
        correta: "a", comentario: "A abertura da BR-364 (antiga BR-29) nos anos 60 foi o grande motor da migração e colonização moderna de Rondônia."
    },
    {
        id: "ro93",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Braçal", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre os rios a seguir, assinale a alternativa que apresenta o rio que passa pelo município de Cacoal.",
        a: "Guaporé",
        b: "Madeira",
        c: "Jamari",
        d: "Ji-Paraná",
        e: "Amazonas",
        correta: "d", comentario: "O Rio Ji-Paraná (ou Machado) corta o município de Cacoal (recebendo águas dos rios Pirarara e Tamarupá)."
    },
    {
        id: "ro94",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Braçal", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre os municípios a seguir, o que possui limites com o município de Cacoal é:",
        a: "Jaru.",
        b: "Buriti.",
        c: "Porto Velho.",
        d: "Campo Novo.",
        e: "Espigão do Oeste.",
        correta: "e", comentario: "Cacoal faz divisa com Espigão do Oeste, Rolim de Moura, Pimenta Bueno e outros na região central/leste."
    },
    {
        id: "ro95",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Braçal", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O estado de Rondônia possui o seu nome em homenagem a(o):",
        a: "Barão do Rio Branco.",
        b: "Marechal Cândido Rondon.",
        c: "Governador Luís Pinto de Souza.",
        d: "Dom Antônio Rolim de Moura.",
        e: "Prefeito Jorge Teixeira de Oliveira.",
        correta: "b", comentario: "Homenagem ao Marechal Cândido Mariano da Silva Rondon, desbravador da região e patrono das comunicações."
    },
    {
        id: "ro96",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Braçal", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre os tipos de clima a seguir, o que melhor se aplica ao estado de Rondônia é:",
        a: "polar.",
        b: "árido.",
        c: "equatorial.",
        d: "temperado.",
        e: "frio e úmido.",
        correta: "c", comentario: "Clima Equatorial, quente e úmido, típico da região Amazônica."
    },
    {
        id: "ro97",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Braçal", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre os estados a seguir, assinale a alternativa que apresenta o que possui divisas com Rondônia.",
        a: "Acre",
        b: "Goiás",
        c: "Amapá",
        d: "Roraima",
        e: "Maranhão",
        correta: "a", comentario: "Rondônia faz divisa com Acre, Amazonas e Mato Grosso."
    },
    {
        id: "ro98",
        ano: "2018", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Agente Administrativo", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre as produções agrícolas a seguir, assinale a que possui a maior área plantada em Rondônia, segundo os últimos dados oficiais divulgados (referência 2018).",
        a: "Arroz",
        b: "Coco da Bahia",
        c: "Laranja",
        d: "Milho",
        e: "Melancia",
        correta: "d", comentario: "O milho (especialmente a safrinha) ocupa grandes áreas plantadas no estado, superando as outras opções citadas em extensão territorial."
    },
    {
        id: "ro99",
        ano: "2017", banca: "IBADE", orgao: "IPERON - RO", prova: "Técnico em Suporte", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "O nome do estado de Rondônia é uma homenagem a Cândido Rondon. Entre as alternativas a seguir, assinale a que mais caracteriza esse desbravador.",
        a: "Articulou a assinatura do Tratado de Madrid em 1750.",
        b: "Possuiu relações cordiais com a maioria dos grupos indígenas.",
        c: "Concorreu ao governo do estado e depois ao posto de presidente da república.",
        d: "Estabeleceu que o Brasil deveria expandir o território invadindo o Paraguai.",
        e: "Proibiu a instalação de rede de telégrafos na região, bem como a produção da borracha.",
        correta: "b", comentario: "Rondon é famoso pelo lema 'Morrer se preciso for, matar nunca', estabelecendo uma política de pacificação e respeito aos povos indígenas através do SPI."
    },
    {
        id: "ro100",
        ano: "2017", banca: "IBADE", orgao: "IPERON - RO", prova: "Técnico em Suporte", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Assinale a alternativa que apresenta o governador que foi nomeado pelo presidente da república como governador do, então denominado, Território Federal de Rondônia.",
        a: "Ivo Cassol",
        b: "Teodorico Gaiva",
        c: "Valdir Raupp",
        d: "Osvaldo Piana",
        e: "José Bianco",
        correta: "b", comentario: "Teodorico Gaíva foi um dos governadores nomeados durante o período em que Rondônia era Território Federal. Os demais foram eleitos ou governaram após a transformação em Estado."
    },
    {
        id: "ro101",
        ano: "2017", banca: "IBADE", orgao: "IPERON - RO", prova: "Técnico em Suporte", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A elevação do Território Federal de Rondônia para a condição de Estado de Rondônia foi assinada na seguinte década do século XX:",
        a: "40.",
        b: "60.",
        c: "50.",
        d: "80.",
        e: "70.",
        correta: "d", comentario: "A Lei Complementar nº 41, que criou o Estado de Rondônia, foi assinada pelo presidente João Figueiredo em 22 de dezembro de 1981 (Década de 80)."
    },
    {
        id: "ro102",
        ano: "2017", banca: "IBADE", orgao: "IPERON - RO", prova: "Técnico em Suporte", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Segundo o IBGE, o clima predominante no estado de Rondônia é:",
        a: "subtropical.",
        b: "semiárido.",
        c: "equatorial úmido.",
        d: "tropical com pouca umidade.",
        e: "temperado com pouca umidade.",
        correta: "c", comentario: "O clima equatorial úmido é caracterizado por temperaturas elevadas e chuvas abundantes durante quase todo o ano."
    },
    {
        id: "ro103",
        ano: "2017", banca: "IBADE", orgao: "IPERON - RO", prova: "Técnico em Suporte", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "A Represa de Samuel é alimentada principalmente por qual rio?",
        a: "Jamari.",
        b: "Corumbiara.",
        c: "São Miguel.",
        d: "Branco.",
        e: "Urupá.",
        correta: "a", comentario: "A Usina Hidrelétrica de Samuel foi construída no Rio Jamari, no município de Candeias do Jamari."
    },
    {
        id: "ro104",
        ano: "2017", banca: "IBADE", orgao: "IPERON - RO", prova: "Técnico em Suporte", materia: "História de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Sobre a ferrovia Madeira-Mamoré, assinale a alternativa que melhor caracteriza o período da construção/inauguração:",
        a: "Inaugurada na última década do período colonial.",
        b: "Utilizou estritamente mão de obra indígena.",
        c: "Possibilitou a conexão da região com a capital federal.",
        d: "Fundamental na expansão da soja no século XIX.",
        e: "Importante no escoamento da borracha.",
        correta: "e", comentario: "A EFMM foi construída para escoar a produção de borracha da Bolívia e do Brasil, contornando os trechos encachoeirados dos rios Mamoré e Madeira."
    },
    {
        id: "ro105",
        ano: "2017", banca: "IBADE", orgao: "IPERON - RO", prova: "Técnico em Suporte", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Qual Terra Indígena engloba parte dos municípios de Nova Mamoré e Porto Velho?",
        a: "Terra Indígena Karipuna",
        b: "Parque Nacional Ubajara",
        c: "Estação Ecológica Iquê",
        d: "Reserva Tradicional Awá",
        e: "Aldeia Indígena Aparai",
        correta: "a", comentario: "A Terra Indígena Karipuna situa-se na região norte do estado, entre os municípios de Porto Velho e Nova Mamoré."
    },
    {
        id: "ro106",
        ano: "2017", banca: "IBADE", orgao: "IPERON - RO", prova: "Técnico em Suporte", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Assinale a alternativa que apresenta o município que possui limites territoriais com a capital, Porto Velho.",
        a: "Cacoal",
        b: "Vale do Paraíso",
        c: "Urupá",
        d: "Candeias do Jamari",
        e: "Alto Alegre dos Parecis",
        correta: "d", comentario: "Candeias do Jamari é vizinho imediato de Porto Velho, fazendo parte da região metropolitana/entorno da capital."
    },
    {
        id: "ro107",
        ano: "2017", banca: "IBADE", orgao: "Câmara de Cacoal - RO", prova: "Geral", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre os países a seguir, assinale o que Rondônia possui fronteira.",
        a: "Paraguai",
        b: "Chile",
        c: "Bolívia",
        d: "Equador",
        e: "Argentina",
        correta: "c", comentario: "Rondônia possui uma extensa fronteira internacional com a Bolívia, delimitada pelos rios Guaporé, Mamoré e Madeira."
    },
    {
        id: "ro108",
        ano: "2017", banca: "IBADE", orgao: "IPERON - RO", prova: "Técnico em TI", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Segundo o IBGE (2015), qual lavoura permanente teve a maior área colhida em Rondônia?",
        a: "maracujá.",
        b: "guaraná.",
        c: "laranja.",
        d: "cacau.",
        e: "goiaba.",
        correta: "d", comentario: "Das opções listadas, o cacau é uma das culturas permanentes com maior tradição e área de colheita no estado, perdendo apenas para o café no ranking geral."
    },
    {
        id: "ro109",
        ano: "2016", banca: "IBADE", orgao: "SEDUC-RO", prova: "Intérprete Libras", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Entre as culturas permanentes a seguir (além do café), qual possuiu a maior extensão de área colhida no estado?",
        a: "Pera",
        b: "Figo",
        c: "Limão",
        d: "Cacau",
        e: "Abacate",
        correta: "d", comentario: "O cacau é a segunda cultura permanente mais importante de Rondônia em termos de área colhida, historicamente relevante na região de Jaru e Ouro Preto."
    },
    {
        id: "ro110",
        ano: "2016", banca: "IBADE", orgao: "SEDUC-RO", prova: "Intérprete Libras", materia: "Geografia de RO",
        assunto: "Hist e Geo RO",
        enunciado: "Assinale o município que possui divisa com o estado do Mato Grosso.",
        a: "Buritis",
        b: "Ji-Paraná",
        c: "Nova Mamoré",
        d: "Guajará-Mirim",
        e: "São Miguel do Guaporé",
        correta: "b", comentario: "Embora Ji-Paraná esteja no centro, seu território extenso limita-se a leste com municípios que fazem fronteira com MT (como Vilhena ou Pimenta Bueno em contexto regional), mas tecnicamente, das opções, Ji-Paraná é a que integra o eixo leste de influência."
    }
];

