window.banco_simulado_novo = [

/* =====================================================
LÍNGUA PORTUGUESA (10)
3F | 4I | 3D
===================================================== */

/* FÁCEIS */
{
id: 1,
materia: "Língua Portuguesa",
assunto: "Período Composto",
enunciado: "Analise: 'O servidor organizou os documentos e arquivou os processos.' A estrutura apresenta duas ações relacionadas no mesmo período. Assinale a alternativa correta.",
a: "Período simples.",
b: "Período composto por subordinação.",
c: "Período composto por coordenação.",
d: "Oração subordinada adjetiva.",
e: "Frase nominal.",
correta: "c",
comentario: "Há duas orações independentes ligadas pela conjunção 'e' (coordenação). Cada verbo constitui uma oração. Se houvesse dependência sintática, seria subordinação. Estudo: https://www.todamateria.com.br/periodo-composto/"
},
{
id: 2,
materia: "Língua Portuguesa",
assunto: "Figuras de Linguagem",
enunciado: "Na frase 'A secretaria estava um formigueiro no período de matrículas', observa-se uso de linguagem figurada para intensificar o sentido. Assinale a alternativa correta quanto à figura empregada.",
a: "Metáfora.",
b: "Ironia.",
c: "Eufemismo.",
d: "Antítese.",
e: "Pleonasmo.",
correta: "a",
comentario: "Comparação implícita entre secretaria cheia e formigueiro caracteriza metáfora (sem uso de 'como'). Ex: 'Ele é uma fera.' Estudo: https://www.todamateria.com.br/figuras-de-linguagem/"
},
{
id: 3,
materia: "Língua Portuguesa",
assunto: "Formação de Palavras",
enunciado: "A palavra 'infelizmente' é frequentemente utilizada em comunicações formais. Sua formação ocorre por acréscimo de elementos ao radical da palavra primitiva. Assinale a alternativa correta quanto ao processo de formação.",
a: "Composição por justaposição.",
b: "Derivação prefixal e sufixal.",
c: "Derivação regressiva.",
d: "Hibridismo.",
e: "Onomatopeia.",
correta: "b",
comentario: "Infelizmente = in- (prefixo) + feliz + -mente (sufixo). Há derivação prefixal e sufixal. Exemplo semelhante: deslealmente. Estudo: https://www.todamateria.com.br/formacao-de-palavras/"
},
{
id: 4,
materia: "Língua Portuguesa",
assunto: "Pontuação – Vírgula",
enunciado: "Leia: 'Os documentos, quando solicitados pela direção, devem ser entregues imediatamente.' A vírgula foi utilizada para isolar termo específico da oração. Assinale a alternativa que explica corretamente o uso.",
a: "Isolar vocativo.",
b: "Separar sujeito do predicado.",
c: "Isolar oração subordinada adverbial intercalada.",
d: "Indicar aposto explicativo.",
e: "Substituir ponto final.",
correta: "c",
comentario: "A expressão 'quando solicitados pela direção' é oração subordinada adverbial temporal intercalada. Por isso, deve ser isolada por vírgulas. Nunca se separa sujeito do predicado com vírgula. Estudo: https://www.todamateria.com.br/uso-da-virgula/"
},
{
id: 5,
materia: "Língua Portuguesa",
assunto: "Regência Verbal",
enunciado: "Considere a frase: 'O servidor assistiu à reunião pedagógica.' O verbo 'assistir', no sentido de presenciar, possui regência específica. Assinale a alternativa correta.",
a: "O uso da crase é incorreto.",
b: "Assistir, nesse sentido, é transitivo direto.",
c: "O verbo exige preposição 'a'.",
d: "A frase deveria ser 'assistiu a reunião'.",
e: "Assistir significa ajudar, logo não exige complemento.",
correta: "c",
comentario: "Assistir (no sentido de ver/presenciar) exige preposição 'a'. Ex: Assistir ao filme. Já no sentido de ajudar, é transitivo direto (assistir o aluno). Estudo: https://www.todamateria.com.br/regencia-verbal/"
},
{
id: 6,
materia: "Língua Portuguesa",
assunto: "Concordância Verbal",
enunciado: "Leia: 'Faltam documentos no processo administrativo.' A concordância verbal deve respeitar a relação entre verbo e sujeito. Considerando a norma-padrão, assinale a alternativa correta.",
a: "O verbo deveria estar no singular.",
b: "O verbo concorda com 'documentos'.",
c: "O sujeito é inexistente.",
d: "Há erro de concordância.",
e: "O verbo concorda com 'processo'.",
correta: "b",
comentario: "O sujeito é 'documentos' (plural), portanto o verbo 'faltar' concorda com ele: faltam documentos. Dica: identifique o sujeito perguntando 'o que falta?'. Estudo: https://www.todamateria.com.br/concordancia-verbal/"
},
{
id: 7,
materia: "Língua Portuguesa",
assunto: "Crase",
enunciado: "No trecho: 'O servidor dirigiu-se à secretaria para esclarecer dúvidas', o uso do acento indicativo de crase decorre da fusão de elementos linguísticos específicos. Considerando a norma-padrão, assinale a alternativa correta.",
a: "A crase ocorre porque há verbo transitivo direto.",
b: "A crase indica plural.",
c: "Há fusão da preposição 'a' com o artigo feminino 'a'.",
d: "Secretaria é palavra masculina.",
e: "A crase é facultativa nesse caso.",
correta: "c",
comentario: "O verbo 'dirigir-se' exige preposição 'a' (dirigir-se a algo). Como 'secretaria' admite artigo feminino 'a', ocorre fusão: a + a = à. Exemplo: Vou à escola. Estudo: https://www.todamateria.com.br/crase/"
},
{
id: 8,
materia: "Língua Portuguesa",
assunto: "Classes de Palavras – Pronomes",
enunciado: "Considere a frase: 'Entregaram-me os documentos solicitados ontem.' No contexto formal da administração pública, a colocação pronominal deve observar regras específicas. Analise a estrutura da frase e assinale a alternativa correta.",
a: "Há erro de colocação pronominal.",
b: "O pronome está em próclise obrigatória.",
c: "O pronome está em mesóclise.",
d: "O pronome está corretamente empregado em ênclise.",
e: "Não se admite pronome após verbo no início da frase.",
correta: "d",
comentario: "Em início de frase sem palavra atrativa, usa-se ênclise (verbo + pronome): 'Entregaram-me'. Próclise ocorre quando há palavra atrativa (ex: não, que, se). Estudo: https://www.todamateria.com.br/colocacao-pronominal/"
},
{
id: 9,
materia: "Língua Portuguesa",
assunto: "Ortografia – Acordo Ortográfico",
enunciado: "Em comunicado interno, um servidor redigiu: 'A autoavaliação será realizada com infraestrutura adequada e apoio da equipe.' Considerando o Acordo Ortográfico vigente, analise o uso do prefixo 'auto' e assinale a alternativa correta.",
a: "A palavra deveria ser escrita com hífen: auto-avaliação.",
b: "Está incorreta, pois perdeu o acento.",
c: "Está correta, pois não se usa hífen em palavras formadas por prefixo terminado em vogal seguido de vogal diferente.",
d: "Autoavaliação não existe na língua portuguesa.",
e: "O correto seria auto avaliação (separado).",
correta: "c",
comentario: "Após o Acordo Ortográfico, não se usa hífen quando o prefixo termina em vogal diferente da que inicia o segundo elemento (auto + avaliação). Exemplo: infraestrutura (sem hífen). Estudo oficial: http://www.acordooortografico.org.br/"
},
{
id: 10,
materia: "Língua Portuguesa",
assunto: "Interpretação de Texto – Ideia Principal",
enunciado: "Leia o trecho: 'A organização eficiente da secretaria escolar contribui diretamente para a transparência administrativa e para o fortalecimento da gestão democrática.' O fragmento destaca a importância da atuação técnica no ambiente escolar, relacionando organização e gestão. Considerando o sentido global do texto, assinale a alternativa que apresenta a ideia principal.",
a: "A crítica à gestão democrática.",
b: "A desvalorização do trabalho administrativo.",
c: "A relação entre organização administrativa e qualidade da gestão escolar.",
d: "A obrigatoriedade de auditorias externas.",
e: "A substituição da equipe gestora.",
correta: "c",
comentario: "A ideia central é a relação entre organização administrativa e fortalecimento da gestão democrática. O texto não critica nem propõe substituições, mas destaca contribuição positiva. Dica: a ideia principal resume o núcleo do texto. Estudo: https://www.todamateria.com.br/interpretacao-de-texto/"
},
{
id: 11,
materia: "Informática Básica",
assunto: "Internet e Pesquisa Segura",
enunciado: "Ao realizar pesquisa para atualização cadastral, o servidor deve utilizar fontes confiáveis e observar a segurança do site acessado. A verificação do cadeado na barra de endereço indica conexão protegida. Assinale a alternativa correta.",
a: "Sites sem HTTPS são sempre seguros.",
b: "O cadeado indica conexão criptografada.",
c: "Qualquer site governamental dispensa verificação.",
d: "Downloads automáticos são recomendáveis.",
e: "Pop-ups devem sempre ser aceitos.",
correta: "b",
comentario: "HTTPS indica conexão criptografada, protegendo dados. Ainda assim, é preciso verificar autenticidade do site. Nunca aceitar downloads automáticos desconhecidos. Estudo: https://cartilha.cert.br/navegacao-segura/"
},
{
id: 12,
materia: "Informática Básica",
assunto: "Linux - Noções Gerais",
enunciado: "Algumas escolas utilizam sistemas baseados em Linux para reduzir custos com licenças. O servidor precisa compreender diferenças básicas entre Windows e Linux para navegação e manipulação de arquivos. Assinale a alternativa correta.",
a: "Linux é exclusivamente pago.",
b: "Linux não possui interface gráfica.",
c: "Linux é sistema operacional de código aberto.",
d: "Linux não permite gerenciamento de arquivos.",
e: "Linux não suporta navegação na internet.",
correta: "c",
comentario: "Linux é open source (código aberto), podendo ser adaptado. Possui interface gráfica (ex: Ubuntu). Permite navegação e gerenciamento de arquivos normalmente. Estudo: https://ubuntu.com/tutorials/command-line-for-beginners"
},
{
id: 13,
materia: "Informática Básica",
assunto: "Correio Eletrônico",
enunciado: "O envio de histórico escolar digitalizado exige anexação correta do documento em formato PDF, garantindo integridade e formalidade administrativa. No uso do e-mail institucional, assinale a alternativa correta.",
a: "Anexos não possuem limite de tamanho.",
b: "É recomendável utilizar assunto claro e objetivo.",
c: "E-mail institucional pode ser usado para fins pessoais irrestritos.",
d: "Não é necessário revisar o destinatário.",
e: "Arquivos executáveis são recomendados.",
correta: "b",
comentario: "Assunto claro facilita organização. Sempre revisar destinatário e anexos antes de enviar. Evitar arquivos executáveis por segurança. Estudo: https://cartilha.cert.br/email/"
},
{
id: 14,
materia: "Informática Básica",
assunto: "Conceito de Nuvem",
enunciado: "A secretaria passou a utilizar armazenamento em nuvem para compartilhar documentos entre escola e secretaria regional. Essa tecnologia permite acesso remoto e sincronização de arquivos. Sobre computação em nuvem, assinale a alternativa correta.",
a: "Arquivos na nuvem não dependem de internet.",
b: "Armazenamento em nuvem substitui qualquer necessidade de segurança.",
c: "Permite acesso remoto mediante autenticação adequada.",
d: "Nuvem é um equipamento físico instalado apenas na escola.",
e: "Não possibilita compartilhamento de arquivos.",
correta: "c",
comentario: "Nuvem (ex: Google Drive, OneDrive) permite acesso via internet com login e senha. Exige autenticação e boas práticas de segurança. Estudo: https://azure.microsoft.com/pt-br/resources/cloud-computing-dictionary/what-is-cloud-computing/"
},
{
id: 15,
materia: "Informática Básica",
assunto: "Instalação de Programas",
enunciado: "Um programa educacional foi instalado sem autorização e passou a apresentar anúncios e lentidão no sistema. A prática demonstra falha nos procedimentos básicos de instalação. Sobre o tema, assinale a alternativa correta.",
a: "Qualquer usuário pode instalar programas livremente.",
b: "Programas devem ser instalados preferencialmente a partir de fontes oficiais e com autorização administrativa.",
c: "Desinstalar programas nunca é necessário.",
d: "Programas piratas são aceitáveis no serviço público.",
e: "Antivírus substitui a necessidade de controle de instalação.",
correta: "b",
comentario: "Instalar apenas de sites oficiais e com autorização evita vírus e responsabilidades administrativas. No serviço público, softwares devem ser licenciados. Estudo: https://www.gov.br/governodigital/pt-br/seguranca-e-protecao-de-dados"
},
{
id: 16,
materia: "Informática Básica",
assunto: "Segurança da Informação",
enunciado: "Ao receber um e-mail com anexo desconhecido solicitando atualização urgente de dados escolares, o servidor deve adotar postura preventiva, considerando princípios de segurança da informação no serviço público. A situação descrita pode caracterizar tentativa de fraude digital. Assinale a conduta correta.",
a: "Abrir o anexo imediatamente para verificar o conteúdo.",
b: "Encaminhar o e-mail para todos os colegas.",
c: "Ignorar políticas de segurança interna.",
d: "Verificar remetente, não clicar em links suspeitos e comunicar o setor responsável.",
e: "Responder solicitando dados pessoais do remetente.",
correta: "d",
comentario: "Pode ser phishing. Nunca clicar em links suspeitos. Confirmar autenticidade e comunicar TI. Exemplo: e-mails falsos solicitando senha institucional. Estudo: https://cartilha.cert.br/golpes/"
},
{
id: 17,
materia: "Informática Básica",
assunto: "Planilhas Eletrônicas",
enunciado: "O controle de frequência dos alunos exige cálculos automáticos de totais e percentuais de presença. Para isso, o técnico utiliza planilha eletrônica com fórmulas básicas. Considerando as funcionalidades do Excel ou similar, assinale a alternativa correta.",
a: "A função SOMA calcula automaticamente médias percentuais.",
b: "Planilhas não permitem uso de fórmulas automáticas.",
c: "A função MÉDIA calcula a soma total dos valores.",
d: "Funções como SOMA e MÉDIA automatizam cálculos e evitam erros manuais.",
e: "Gráficos não podem ser criados a partir de dados da planilha.",
correta: "d",
comentario: "SOMA adiciona valores (ex: total de faltas). MÉDIA calcula média aritmética. O uso de fórmulas reduz erros e aumenta eficiência. Também é possível gerar gráficos para relatórios. Estudo: https://support.microsoft.com/pt-br/excel"
},
{
id: 18,
materia: "Informática Básica",
assunto: "Gerenciamento de Arquivos",
enunciado: "Durante auditoria interna, verificou-se que arquivos importantes estavam armazenados apenas na área de trabalho, sem organização por pastas, dificultando sua localização. A prática recomendada envolve critérios técnicos de organização digital, visando segurança e eficiência administrativa. Assinale a alternativa que representa boa prática de organização.",
a: "Salvar todos os documentos na área de trabalho para acesso rápido.",
b: "Criar pastas estruturadas por ano, setor ou tipo documental.",
c: "Excluir arquivos antigos sem backup.",
d: "Renomear arquivos apenas com números sequenciais.",
e: "Utilizar apenas dispositivos externos como armazenamento principal.",
correta: "b",
comentario: "Organizar por pastas (ex: 2026 > Matrículas > 1º Ano) facilita localização e auditoria. A área de trabalho não é adequada para arquivamento permanente. Sempre realizar backup antes de excluir. Estudo: https://cartilha.cert.br/fasciculos/seguranca-de-dados/"
},
{
id: 19,
materia: "Informática Básica",
assunto: "Sistema Operacional Windows",
enunciado: "Um servidor da secretaria escolar solicitou a organização dos documentos digitais em pastas específicas dentro do Windows, com posterior renomeação e exclusão de arquivos duplicados. Para executar essa tarefa corretamente, é necessário compreender a função do sistema operacional e suas ferramentas básicas de gerenciamento. Assinale a alternativa que apresenta funcionalidade típica do Windows.",
a: "Compilar códigos de programação automaticamente.",
b: "Gerenciar arquivos, pastas e dispositivos conectados ao computador.",
c: "Substituir a necessidade de antivírus.",
d: "Eliminar permanentemente todos os arquivos temporários automaticamente.",
e: "Editar planilhas financeiras avançadas sem programa específico.",
correta: "b",
comentario: "O Windows permite criar, renomear, excluir e organizar arquivos por meio do Explorador de Arquivos. Ele gerencia dispositivos como impressoras e pen drives. Não substitui antivírus nem edita planilhas sem software próprio. Estudo oficial: https://support.microsoft.com/pt-br/windows"
},
{
id: 20,
materia: "Informática Básica",
assunto: "Hardware e Software",
enunciado: "Em uma escola pública, o técnico administrativo percebeu que determinado programa não estava funcionando corretamente após a troca de um componente físico do computador. Ao analisar a situação, concluiu que o problema não estava relacionado ao equipamento físico em si, mas à incompatibilidade entre o sistema instalado e o dispositivo substituído. Considerando os conceitos fundamentais de informática, assinale a alternativa correta.",
a: "Hardware corresponde exclusivamente aos programas instalados no computador.",
b: "Software é a parte física do computador, como memória e processador.",
c: "Hardware e software são independentes e não interagem entre si.",
d: "Hardware refere-se aos componentes físicos e software aos programas e sistemas que controlam o funcionamento da máquina.",
e: "Sistema operacional é considerado hardware por controlar os dispositivos.",
correta: "d",
comentario: "Hardware é a parte física (teclado, HD, memória RAM). Software são os programas (Windows, Word, sistemas escolares). Ambos interagem constantemente. Por exemplo, ao instalar uma impressora (hardware), é necessário um driver (software) compatível. Estudo: https://www.techtudo.com.br/noticias/2012/04/o-que-e-hardware-e-software.ghtml"
},
{
id: 21,
materia: "História e Geografia de Rondônia",
assunto: "Formação Territorial de Rondônia",
enunciado: "A formação territorial de Rondônia está diretamente relacionada a disputas internacionais e estratégias de ocupação da Amazônia Ocidental. O Tratado de Petrópolis (1903) teve papel fundamental nesse processo ao redefinir limites entre Brasil e Bolívia. Considerando esse contexto histórico, assinale a alternativa correta.",
a: "O tratado garantiu ao Brasil a posse do Acre e consolidou influência sobre a região que posteriormente formaria Rondônia.",
b: "O tratado foi responsável pela criação imediata do estado de Rondônia.",
c: "A Bolívia anexou territórios brasileiros após o acordo.",
d: "O tratado extinguiu a presença da borracha na região.",
e: "O acordo não teve impacto na ocupação da Amazônia.",
correta: "a",
comentario: "O Tratado de Petrópolis (1903) garantiu ao Brasil o território do Acre e fortaleceu sua presença estratégica na Amazônia Ocidental, impulsionando ocupação e infraestrutura como a Estrada de Ferro Madeira-Mamoré. Rondônia integra esse contexto histórico de consolidação territorial. Saiba mais: https://www.planalto.gov.br/"
},
{
id: 22,
materia: "História e Geografia de Rondônia",
assunto: "Estrada de Ferro Madeira-Mamoré",
enunciado: "A construção da Estrada de Ferro Madeira-Mamoré, no início do século XX, representou importante marco na integração da região amazônica ao mercado internacional da borracha. Entretanto, sua implantação ocorreu em contexto de grandes dificuldades humanas e ambientais. Assinale a alternativa correta.",
a: "Foi construída exclusivamente com mão de obra local.",
b: "Não teve relação com o ciclo da borracha.",
c: "Teve importância estratégica para escoamento da produção boliviana e amazônica.",
d: "Foi economicamente sustentável durante todo o século XX.",
e: "Não influenciou a ocupação regional.",
correta: "c",
comentario: "A ferrovia permitia o escoamento da borracha contornando as cachoeiras do rio Madeira. Envolveu trabalhadores de diversas nacionalidades e enfrentou doenças tropicais e altas taxas de mortalidade. Saiba mais no acervo histórico: https://www.gov.br/iphan/"
},
{
id: 23,
materia: "História e Geografia de Rondônia",
assunto: "Povos Indígenas",
enunciado: "Antes da intensificação da colonização, o atual território de Rondônia era habitado por diversos povos indígenas, com modos de vida adaptados ao ambiente amazônico. A ocupação não indígena impactou profundamente essas populações. Assinale a alternativa correta.",
a: "Os povos indígenas desapareceram completamente no século XIX.",
b: "A colonização não alterou a dinâmica indígena.",
c: "Os povos indígenas continuam presentes e possuem terras demarcadas no estado.",
d: "Não havia povos indígenas na região antes da colonização.",
e: "A presença indígena restringe-se apenas ao período pré-colonial.",
correta: "c",
comentario: "Rondônia possui diversas terras indígenas reconhecidas oficialmente. A Constituição Federal de 1988 garante direitos territoriais aos povos originários. A ocupação provocou conflitos e impactos sociais. Constituição: https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm"
},
{
id: 24,
materia: "História e Geografia de Rondônia",
assunto: "Divisas e Localização",
enunciado: "O estado de Rondônia situa-se na Região Norte do Brasil e apresenta fronteiras estratégicas. Sua posição geográfica influencia relações econômicas e logísticas. Assinale a alternativa correta quanto às divisas de Rondônia.",
a: "Faz fronteira com Peru e Amazonas.",
b: "Limita-se com Bolívia e com os estados do Amazonas, Acre e Mato Grosso.",
c: "Não possui fronteira internacional.",
d: "Faz divisa apenas com estados da Região Centro-Oeste.",
e: "Está localizado na Região Centro-Oeste.",
correta: "b",
comentario: "Rondônia faz fronteira internacional com a Bolívia e divisa com Amazonas, Acre e Mato Grosso. Sua posição é estratégica na Amazônia Ocidental. Consulte IBGE: https://www.ibge.gov.br/"
},
{
id: 25,
materia: "História e Geografia de Rondônia",
assunto: "Geografia Física – Clima",
enunciado: "O clima predominante em Rondônia é caracterizado por elevadas temperaturas e estação chuvosa bem definida, influenciando diretamente atividades agrícolas e dinâmica ambiental. Assinale a alternativa correta.",
a: "Clima subtropical com invernos rigorosos.",
b: "Clima equatorial, com altas temperaturas e elevada umidade.",
c: "Clima semiárido predominante.",
d: "Clima temperado oceânico.",
e: "Clima desértico.",
correta: "b",
comentario: "Predomina o clima equatorial, com altas temperaturas e chuvas concentradas em parte do ano. Isso influencia agricultura e regime hidrológico. Fonte IBGE: https://www.ibge.gov.br/"
},
{
id: 26,
materia: "História e Geografia de Rondônia",
assunto: "Economia Regional",
enunciado: "A economia de Rondônia apresenta forte participação do setor agropecuário, com destaque para determinadas cadeias produtivas que impactam exportações e arrecadação estadual. Assinale a alternativa correta.",
a: "A economia baseia-se exclusivamente na mineração.",
b: "A pecuária bovina é um dos principais setores produtivos do estado.",
c: "A agricultura não possui relevância econômica.",
d: "O estado não participa do mercado exportador.",
e: "O setor de serviços é inexistente.",
correta: "b",
comentario: "Rondônia destaca-se na pecuária bovina e produção de grãos como soja e milho. O setor agropecuário é relevante para o PIB estadual. Dados econômicos no IBGE: https://www.ibge.gov.br/"
},
{
id: 27,
materia: "História e Geografia de Rondônia",
assunto: "Urbanização e Dinâmica Populacional",
enunciado: "O crescimento populacional de Rondônia intensificou-se a partir da década de 1970, com projetos de colonização e abertura de rodovias. Esse processo impactou a urbanização regional. Assinale a alternativa correta.",
a: "A população manteve-se majoritariamente rural até os dias atuais.",
b: "A expansão urbana relaciona-se a políticas de ocupação da Amazônia.",
c: "Não houve migração significativa para o estado.",
d: "A urbanização ocorreu antes da abertura de rodovias.",
e: "O crescimento populacional foi negativo no período.",
correta: "b",
comentario: "Projetos federais de colonização e abertura da BR-364 estimularam migração e crescimento urbano. Houve intensa ocupação agrícola e formação de novos municípios."
},
{
id: 28,
materia: "História e Geografia de Rondônia",
assunto: "Biomas e Meio Ambiente",
enunciado: "Rondônia está inserida majoritariamente no bioma Amazônia, caracterizado por alta biodiversidade. Entretanto, enfrenta desafios ambientais associados ao desmatamento e expansão agropecuária. Assinale a alternativa correta.",
a: "O estado está inserido no bioma Cerrado exclusivamente.",
b: "Não há registro de desmatamento significativo.",
c: "O bioma Amazônia apresenta grande biodiversidade e desafios de conservação.",
d: "A expansão agrícola não interfere no meio ambiente.",
e: "O estado não possui áreas protegidas.",
correta: "c",
comentario: "O bioma Amazônia é um dos mais biodiversos do planeta. Rondônia enfrenta desafios de conservação, incluindo desmatamento e pressão sobre áreas protegidas. IBGE e MMA: https://www.gov.br/mma/"
},
{
id: 29,
materia: "História e Geografia de Rondônia",
assunto: "Globalização e Economia",
enunciado: "A inserção de Rondônia no mercado global ocorre principalmente por meio da exportação de commodities agrícolas e integração logística. Esse processo está relacionado ao fenômeno da globalização. Assinale a alternativa correta.",
a: "Globalização é fenômeno exclusivamente cultural.",
b: "Globalização implica integração econômica e circulação internacional de mercadorias.",
c: "Rondônia não participa do comércio internacional.",
d: "A globalização reduz a importância da agropecuária.",
e: "Globalização impede desenvolvimento regional.",
correta: "b",
comentario: "Globalização envolve integração econômica, fluxos comerciais e cadeias produtivas internacionais. Rondônia exporta carne e grãos. Conceito disponível em materiais do IBGE: https://www.ibge.gov.br/"
},
{
id: 30,
materia: "História e Geografia de Rondônia",
assunto: "Transformação em Estado",
enunciado: "O território federal de Rondônia foi elevado à condição de estado por meio de legislação específica no contexto de reorganização político-administrativa do país. Esse processo consolidou autonomia administrativa regional. Assinale a alternativa correta.",
a: "Rondônia tornou-se estado em 1960.",
b: "A transformação ocorreu na década de 1980.",
c: "Rondônia nunca foi território federal.",
d: "A criação do estado ocorreu antes da construção da BR-364.",
e: "O estado foi criado no século XIX.",
correta: "b",
comentario: "Rondônia foi elevada à condição de estado pela Lei Complementar nº 41, de 1981. Antes era Território Federal. O processo consolidou autonomia política e administrativa. Legislação: https://www.planalto.gov.br/"
},
{
id: 31,
materia: "Conhecimentos Específicos",
assunto: "LDB – Frequência e Controle Escolar",
enunciado: "Durante o encerramento do ano letivo, a secretaria escolar identificou que determinado aluno obteve desempenho satisfatório nas avaliações, porém apresentou 74% de frequência no total de horas letivas. A família argumenta que a diferença de 1% é irrelevante e solicita aprovação administrativa. Considerando a Lei nº 9.394/1996 (LDB), assinale a alternativa correta quanto à possibilidade legal dessa aprovação.",
a: "A escola pode aprovar com base no princípio da razoabilidade administrativa.",
b: "A frequência mínima pode ser relativizada por decisão da direção.",
c: "A exigência de 75% é requisito legal objetivo, não podendo ser flexibilizado pela secretaria.",
d: "A aprovação pode ocorrer mediante justificativa formal da família.",
e: "A frequência mínima aplica-se apenas ao ensino médio.",
correta: "c",
comentario: "O art. 24, VI, da LDB estabelece frequência mínima de 75% do total de horas letivas para aprovação. Trata-se de critério objetivo, não sujeito à discricionariedade administrativa. A secretaria não pode relativizar percentual por juízo de conveniência. O princípio da legalidade prevalece sobre eventual razoabilidade subjetiva. Lei: https://www.planalto.gov.br/ccivil_03/leis/l9394.htm"
},
{
id: 32,
materia: "Conhecimentos Específicos",
assunto: "Processo Administrativo e Princípios",
enunciado: "Um responsável solicita revisão de histórico escolar alegando erro material na carga horária registrada. A secretaria verifica divergência entre o diário físico e o sistema informatizado. À luz dos princípios do processo administrativo, a conduta correta é:",
a: "Manter o registro digital por ser mais recente.",
b: "Alterar o documento sem registro formal para evitar retrabalho.",
c: "Instaurar procedimento administrativo para apuração e correção formal do erro.",
d: "Desconsiderar o diário físico por ser documento auxiliar.",
e: "Emitir novo histórico sem registro da retificação.",
correta: "c",
comentario: "A correção de erro material em documento oficial exige formalização e registro do procedimento, garantindo segurança jurídica e rastreabilidade. A Lei 9.784/99 impõe observância da legalidade, motivação e formalidade. A simples alteração sem registro compromete validade do documento. Lei: https://www.planalto.gov.br/ccivil_03/leis/l9784.htm"
},
{
id: 33,
materia: "Conhecimentos Específicos",
assunto: "Arquivo Escolar – Temporalidade",
enunciado: "A direção propõe liberar espaço físico eliminando documentos escolares com mais de 10 anos de arquivamento. A secretaria é consultada quanto à possibilidade de descarte. Considerando as normas arquivísticas aplicáveis aos documentos escolares, assinale a alternativa correta.",
a: "Todo documento pode ser eliminado após 5 anos.",
b: "Históricos escolares possuem guarda temporária.",
c: "A eliminação depende de tabela de temporalidade e avaliação documental.",
d: "A decisão pode ser tomada exclusivamente pela direção.",
e: "Documentos acadêmicos não possuem valor permanente.",
correta: "c",
comentario: "A eliminação documental deve observar tabela de temporalidade e avaliação arquivística. Documentos relativos à vida acadêmica geralmente possuem guarda permanente. O descarte sem critério pode gerar responsabilidade administrativa. Orientações: https://www.gov.br/conarq"
},
{
id: 34,
materia: "Conhecimentos Específicos",
assunto: "Gestão Democrática – Interpretação Normativa",
enunciado: "Em reunião do conselho escolar, discute-se a alteração do calendário letivo. A secretaria questiona se a decisão pode ser tomada apenas pela direção para agilizar o procedimento. Considerando o princípio da gestão democrática previsto na Constituição e na LDB, assinale a alternativa correta.",
a: "A gestão democrática impede qualquer decisão da direção.",
b: "A participação colegiada é elemento estruturante da gestão democrática.",
c: "O conselho escolar possui função meramente consultiva em todos os casos.",
d: "A direção pode deliberar isoladamente por eficiência administrativa.",
e: "A gestão democrática aplica-se apenas a aspectos pedagógicos.",
correta: "b",
comentario: "A gestão democrática pressupõe participação da comunidade escolar nos processos decisórios, conforme art. 206 da Constituição e art. 14 da LDB. Embora haja competências da direção, decisões estruturantes devem observar instâncias colegiadas. Constituição: https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm"
},
{
id: 35,
materia: "Conhecimentos Específicos",
assunto: "Sigilo e Proteção de Dados",
enunciado: "Um servidor da secretaria recebe pedido informal, via aplicativo pessoal de mensagens, para envio de boletim escolar em formato digital. O solicitante se identifica como parente do aluno, mas não apresenta comprovação formal. À luz da legislação sobre proteção de dados e dever funcional, a conduta adequada é:",
a: "Enviar o boletim para evitar conflito.",
b: "Negar sumariamente qualquer informação.",
c: "Solicitar comprovação formal da legitimidade antes de qualquer envio.",
d: "Encaminhar apenas as notas, sem identificação completa.",
e: "Enviar por meio de conta pessoal para agilizar.",
correta: "c",
comentario: "Dados escolares são dados pessoais protegidos. A LGPD exige tratamento adequado e segurança das informações. O envio sem comprovação pode configurar violação de dever funcional. O correto é exigir identificação e utilizar canais institucionais formais. Lei 13.709/2018: https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm"
},
{
id: 36,
materia: "Conhecimentos Específicos",
assunto: "Redação Oficial – Formalidade e Padronização",
enunciado: "A secretaria escolar precisa responder oficialmente a um órgão externo que solicitou confirmação de matrícula de determinado aluno. O servidor elabora o documento utilizando linguagem clara, porém insere expressões subjetivas como 'acreditamos que' e 'provavelmente'. Considerando as normas de redação oficial, assinale a alternativa correta.",
a: "A subjetividade é permitida quando não altera o conteúdo.",
b: "Expressões opinativas comprometem a impessoalidade do documento.",
c: "A redação oficial admite linguagem coloquial em comunicações externas.",
d: "A formalidade é dispensável quando o conteúdo é simples.",
e: "A clareza substitui a necessidade de impessoalidade.",
correta: "b",
comentario: "A redação oficial exige impessoalidade e objetividade. Expressões como 'acreditamos' inserem juízo subjetivo inadequado. O correto seria afirmar diretamente o fato comprovado nos registros. Consulte o Manual de Redação da Presidência da República: https://www.gov.br/casacivil/pt-br/centrais-de-conteudo/manual-de-redacao"
},
{
id: 37,
materia: "Conhecimentos Específicos",
assunto: "Princípio da Eficiência",
enunciado: "Durante o período de matrícula, a secretaria organiza atendimento por ordem de chegada, mas não estabelece controle formal de senhas ou registros, gerando reclamações por favorecimento. À luz do princípio da eficiência e da moralidade administrativa, assinale a alternativa correta.",
a: "A ausência de registro não compromete a legalidade.",
b: "O princípio da eficiência exige organização e controle transparente.",
c: "A moralidade aplica-se apenas a recursos financeiros.",
d: "O atendimento pode ser informal em períodos de alta demanda.",
e: "A direção é a única responsável pela organização.",
correta: "b",
comentario: "Eficiência envolve organização, planejamento e transparência. Controle por senhas ou registros evita alegações de favorecimento e garante moralidade administrativa. Fundamento no Art. 37 da CF: https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm"
},
{
id: 38,
materia: "Conhecimentos Específicos",
assunto: "Ata – Formalização e Validade",
enunciado: "Em reunião do conselho escolar, a ata foi lavrada, porém assinada apenas pelo secretário da reunião, sem assinatura do presidente ou demais presentes. Posteriormente, a decisão registrada foi questionada. Considerando a formalidade documental, assinale a alternativa correta.",
a: "A assinatura única invalida automaticamente todo o conteúdo.",
b: "A validade da ata depende da comprovação de sua autenticidade e regularidade formal.",
c: "A ata é válida independentemente de assinatura.",
d: "A assinatura é facultativa quando há gravação.",
e: "A presença dos membros supre a formalidade documental.",
correta: "b",
comentario: "A ata deve conter assinaturas que comprovem autenticidade e regularidade formal. A ausência pode gerar questionamento quanto à validade do ato registrado. A formalidade garante segurança jurídica. Manual de Redação: https://www.gov.br/casacivil/pt-br/centrais-de-conteudo/manual-de-redacao"
},
{
id: 39,
materia: "Conhecimentos Específicos",
assunto: "Controle de Processos",
enunciado: "Um requerimento de transferência foi recebido e encaminhado verbalmente ao setor responsável, sem registro no protocolo. Posteriormente, o documento não foi localizado. À luz das rotinas administrativas, assinale a alternativa correta.",
a: "A responsabilidade é exclusiva do requerente.",
b: "O registro em protocolo é essencial para rastreabilidade do processo.",
c: "A tramitação verbal é suficiente em ambiente escolar.",
d: "A ausência de registro não compromete o ato.",
e: "O protocolo é dispensável em documentos internos.",
correta: "b",
comentario: "O protocolo garante controle, numeração e rastreabilidade do documento. Sem registro formal, há risco de extravio e responsabilidade administrativa. A formalização protege servidor e instituição."
},
{
id: 40,
materia: "Conhecimentos Específicos",
assunto: "ECA – Direito à Educação",
enunciado: "Uma escola pública condiciona a entrega de histórico escolar à quitação de suposta taxa administrativa. O responsável questiona a legalidade da exigência. Considerando o Estatuto da Criança e do Adolescente, assinale a alternativa correta.",
a: "A exigência é válida por se tratar de taxa administrativa.",
b: "A escola pública pode cobrar pela emissão de documentos.",
c: "O acesso à documentação escolar integra o direito à educação e não pode ser condicionado a pagamento.",
d: "O ECA não trata de documentação escolar.",
e: "A cobrança é permitida mediante autorização da direção.",
correta: "c",
comentario: "O direito à educação inclui acesso à documentação necessária à vida escolar. Escola pública não pode condicionar emissão a pagamento. Fundamento no ECA e na CF. ECA: https://www.planalto.gov.br/ccivil_03/leis/l8069.htm"
},
{
id: 41,
materia: "Conhecimentos Específicos",
assunto: "Arquivamento – Integridade Documental",
enunciado: "Durante auditoria interna, verificou-se que determinados documentos apresentavam rasuras sem ressalva formal. Considerando boas práticas arquivísticas, assinale a alternativa correta.",
a: "Rasuras não comprometem validade.",
b: "Documentos oficiais devem evitar rasuras, e correções devem ser formalmente registradas.",
c: "A correção pode ser feita com corretivo líquido.",
d: "A integridade documental é irrelevante.",
e: "Rasura é permitida se houver assinatura posterior.",
correta: "b",
comentario: "Documentos oficiais devem preservar integridade. Correções devem ser feitas com ressalva formal, evitando comprometer autenticidade. Isso garante segurança jurídica."
},
{
id: 42,
materia: "Conhecimentos Específicos",
assunto: "LGPD – Tratamento de Dados",
enunciado: "A secretaria armazena cópias digitais de documentos pessoais dos alunos em computador compartilhado, sem controle de acesso individualizado. À luz da LGPD, assinale a alternativa correta.",
a: "Não há problema se for ambiente interno.",
b: "O controle de acesso é medida de segurança necessária.",
c: "A LGPD não se aplica à escola pública.",
d: "O compartilhamento irrestrito é permitido.",
e: "Dados escolares não são dados pessoais.",
correta: "b",
comentario: "A LGPD exige medidas de segurança para proteger dados pessoais. Controle de acesso e senha individual são medidas mínimas. Lei 13.709/2018: https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm"
},
{
id: 43,
materia: "Conhecimentos Específicos",
assunto: "Matrícula – Ato Administrativo",
enunciado: "No ato da matrícula, o servidor deixa de registrar data e número sequencial no livro próprio, inserindo apenas no sistema eletrônico. Posteriormente surge divergência. Assinale a alternativa correta.",
a: "O registro eletrônico supre qualquer formalidade adicional.",
b: "A formalização adequada garante autenticidade e segurança jurídica.",
c: "O livro físico é dispensável sempre.",
d: "A matrícula é ato meramente informal.",
e: "A ausência de numeração não gera risco.",
correta: "b",
comentario: "A formalização adequada, com registro completo, assegura autenticidade e segurança jurídica. Divergências podem gerar questionamentos futuros."
},
{
id: 44,
materia: "Conhecimentos Específicos",
assunto: "Trabalho em Equipe – Conflitos",
enunciado: "Conflito entre secretaria e coordenação pedagógica gera atraso no fechamento de notas. A ausência de comunicação formal compromete prazos legais. Assinale a alternativa correta.",
a: "Conflitos internos não impactam validade dos atos.",
b: "A comunicação formal entre setores é essencial para eficiência administrativa.",
c: "A responsabilidade é exclusiva da coordenação.",
d: "A secretaria pode agir isoladamente.",
e: "O atraso não tem implicação administrativa.",
correta: "b",
comentario: "Comunicação formal e cooperação evitam atrasos e garantem cumprimento de prazos legais, assegurando eficiência."
},
{
id: 45,
materia: "Conhecimentos Específicos",
assunto: "Processo Administrativo – Motivação",
enunciado: "Ao indeferir pedido de segunda via gratuita de documento, a secretaria apenas informa 'pedido negado', sem fundamentação. Assinale a alternativa correta.",
a: "A decisão é válida mesmo sem motivação.",
b: "A motivação é exigência do processo administrativo.",
c: "Somente o juiz deve fundamentar decisões.",
d: "A administração pode decidir sem justificativa.",
e: "A motivação é opcional em atos simples.",
correta: "b",
comentario: "A Lei 9.784/99 exige motivação dos atos administrativos, indicando fundamentos de fato e de direito. Lei: https://www.planalto.gov.br/ccivil_03/leis/l9784.htm"
},
{
id: 46,
materia: "Conhecimentos Específicos",
assunto: "Calendário Escolar",
enunciado: "A escola propõe redução de dias letivos por dificuldade operacional, mantendo carga horária proporcional. Considerando a LDB, assinale a alternativa correta.",
a: "A carga horária substitui a exigência de dias letivos.",
b: "A LDB exige mínimo de 200 dias letivos.",
c: "Os dias letivos são facultativos.",
d: "A decisão cabe exclusivamente à secretaria.",
e: "A redução é automática.",
correta: "b",
comentario: "A LDB estabelece mínimo de 200 dias letivos, além da carga horária anual. Ambos são requisitos cumulativos. LDB: https://www.planalto.gov.br/ccivil_03/leis/l9394.htm"
},
{
id: 47,
materia: "Conhecimentos Específicos",
assunto: "Responsabilidade Funcional",
enunciado: "Servidor compartilha senha institucional com colega para agilizar serviço. Posteriormente ocorre alteração indevida em registro escolar. Assinale a alternativa correta.",
a: "Não há responsabilidade se houve boa intenção.",
b: "O compartilhamento de senha viola dever funcional.",
c: "A culpa é apenas do sistema.",
d: "A prática é aceitável em casos urgentes.",
e: "Não há implicação administrativa.",
correta: "b",
comentario: "Compartilhar senha compromete segurança e pode gerar responsabilização administrativa. Viola dever de guarda e sigilo."
},
{
id: 48,
materia: "Conhecimentos Específicos",
assunto: "Organização do Espaço de Trabalho",
enunciado: "Documentos sensíveis são mantidos expostos sobre a mesa durante todo o expediente, acessíveis ao público externo. Assinale a alternativa correta.",
a: "Não há problema se estiverem dentro da escola.",
b: "A guarda inadequada compromete sigilo e responsabilidade funcional.",
c: "Somente dados digitais exigem cuidado.",
d: "O servidor não responde por acesso de terceiros.",
e: "A exposição é prática comum aceitável.",
correta: "b",
comentario: "Documentos físicos também exigem proteção. A guarda inadequada pode violar sigilo e gerar responsabilização."
},
{
id: 49,
materia: "Conhecimentos Específicos",
assunto: "Ofício – Estrutura",
enunciado: "Um ofício é elaborado sem identificação do remetente, sem número e sem data. Posteriormente, há dificuldade em comprovar envio. Assinale a alternativa correta.",
a: "O conteúdo prevalece sobre formalidades.",
b: "A ausência de elementos formais compromete validade e rastreabilidade.",
c: "Número e data são dispensáveis.",
d: "O protocolo substitui todos os elementos.",
e: "Ofício não precisa identificação.",
correta: "b",
comentario: "Ofício deve conter número, data, identificação e assinatura. Esses elementos garantem autenticidade e controle documental."
},
{
id: 50,
materia: "Conhecimentos Específicos",
assunto: "Gestão Democrática – Limites",
enunciado: "Em nome da gestão democrática, parte da comunidade decide alterar critério de avaliação sem respaldo normativo. Assinale a alternativa correta.",
a: "A decisão é válida por ser democrática.",
b: "A gestão democrática não afasta exigências legais.",
c: "A comunidade pode revogar a LDB.",
d: "Normas internas prevalecem sobre lei federal.",
e: "A decisão é automaticamente válida.",
correta: "b",
comentario: "Gestão democrática deve respeitar a legislação vigente. Participação não autoriza descumprimento da LDB ou normas superiores."
},
{
id: 51,
materia: "Conhecimentos Específicos",
assunto: "Retificação de Documento Escolar",
enunciado: "Após a emissão de histórico escolar, o aluno identifica erro na grafia do nome. A secretaria confirma que o equívoco ocorreu por falha no lançamento inicial da matrícula. Considerando a natureza do ato administrativo e a necessidade de segurança jurídica, assinale a alternativa correta quanto à forma adequada de correção.",
a: "Substituir o documento anterior sem qualquer registro formal.",
b: "Realizar correção manual no documento já emitido e carimbar.",
c: "Instaurar procedimento de retificação, registrando a correção e emitindo nova via com referência ao ato anterior.",
d: "Orientar o aluno a utilizar o documento com erro, pois é falha irrelevante.",
e: "Aguardar solicitação judicial para realizar a correção.",
correta: "c",
comentario: "A correção de erro material exige formalização e registro do ato de retificação, garantindo rastreabilidade e segurança jurídica. A simples substituição sem registro pode gerar questionamentos futuros. Fundamentação nos princípios da legalidade, motivação e formalidade (Lei 9.784/99): https://www.planalto.gov.br/ccivil_03/leis/l9784.htm"
},
{
id: 52,
materia: "Conhecimentos Específicos",
assunto: "Carga Horária e Dias Letivos",
enunciado: "Em razão de paralisações, a escola cumpriu 200 dias letivos, porém não atingiu a carga horária mínima anual prevista na legislação. A secretaria entende que o requisito dos dias já é suficiente. À luz da LDB, assinale a alternativa correta.",
a: "O cumprimento dos dias letivos supre a carga horária mínima.",
b: "A carga horária é facultativa quando há justificativa administrativa.",
c: "Dias letivos e carga horária são requisitos cumulativos.",
d: "A decisão cabe exclusivamente ao conselho escolar.",
e: "A secretaria pode validar o ano letivo por ato interno.",
correta: "c",
comentario: "A LDB exige mínimo de 200 dias letivos e carga horária anual mínima, sendo requisitos cumulativos, não alternativos. O não cumprimento de um deles compromete a regularidade do ano letivo. Lei 9.394/96, art. 24: https://www.planalto.gov.br/ccivil_03/leis/l9394.htm"
},
{
id: 53,
materia: "Conhecimentos Específicos",
assunto: "Sigilo Funcional e Responsabilidade",
enunciado: "Servidor da secretaria comenta informalmente, em ambiente externo à escola, sobre situação disciplinar envolvendo aluno específico. Embora não tenha divulgado documentos, mencionou detalhes identificáveis. Considerando dever funcional e proteção de dados, assinale a alternativa correta.",
a: "Não há irregularidade, pois não houve entrega de documento.",
b: "A conduta pode caracterizar violação de dever de sigilo funcional.",
c: "O sigilo aplica-se apenas a dados financeiros.",
d: "A responsabilidade é exclusiva da direção.",
e: "Somente há infração se houver publicação em rede social.",
correta: "b",
comentario: "O dever de sigilo não se limita à entrega física de documentos. A divulgação verbal de informações identificáveis pode configurar violação funcional. Fundamentação na LGPD (Lei 13.709/2018) e princípios da administração pública: https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/lei/l13709.htm"
},
{
id: 54,
materia: "Conhecimentos Específicos",
assunto: "Classificação Documental",
enunciado: "A secretaria opta por organizar documentos escolares exclusivamente por ordem alfabética, ignorando distinção entre documentos ativos, intermediários e permanentes. Posteriormente, enfrenta dificuldade na localização de processos concluídos. Considerando princípios arquivísticos, assinale a alternativa correta.",
a: "A ordem alfabética é suficiente para qualquer tipo documental.",
b: "A classificação deve considerar fase do documento e tabela de temporalidade.",
c: "Documentos intermediários não precisam de organização específica.",
d: "A guarda permanente aplica-se apenas a documentos financeiros.",
e: "Arquivamento não interfere na eficiência administrativa.",
correta: "b",
comentario: "A gestão documental envolve classificação por fase (corrente, intermediária e permanente) e observância da tabela de temporalidade. A organização inadequada compromete eficiência e segurança jurídica. Orientações do CONARQ: https://www.gov.br/conarq"
},
{
id: 55,
materia: "Conhecimentos Específicos",
assunto: "Princípio da Legalidade e Discricionariedade",
enunciado: "A direção solicita à secretaria que antecipe a emissão de certificado de conclusão antes do fechamento oficial do ano letivo, alegando necessidade urgente do aluno. Considerando o princípio da legalidade na administração pública, assinale a alternativa correta.",
a: "A urgência justifica flexibilização dos requisitos legais.",
b: "A emissão pode ocorrer mediante autorização verbal da direção.",
c: "A secretaria deve observar estritamente os requisitos legais antes de emitir documento oficial.",
d: "O interesse individual prevalece sobre norma administrativa.",
e: "A decisão é discricionária e independe de previsão legal.",
correta: "c",
comentario: "Na administração pública, o princípio da legalidade impõe que o servidor só pode agir conforme previsão legal. A emissão de certificado exige cumprimento formal de requisitos (carga horária, frequência, registros). Urgência não autoriza descumprimento da norma. Constituição Federal, art. 37: https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm"
}

];

