window.banco_simulado_novo = [

/* =====================================================
LÍNGUA PORTUGUESA (10)
3F | 4I | 3D
===================================================== */

/* FÁCEIS */
{
id: "sim01",
materia: "Conhecimentos Específicos",
assunto: "Higiene e Assepsia em Ambiente Escolar",
enunciado: "Em uma escola pública com grande circulação de alunos, foi identificado aumento de casos de infecções respiratórias. A equipe de limpeza recebeu orientação para intensificar procedimentos de higienização das superfícies mais tocadas. Considerando os princípios de higiene e assepsia, a medida mais adequada para reduzir a carga microbiana nesses pontos é:",
a: "Realizar limpeza mecânica com água e detergente neutro antes da aplicação de desinfetante apropriado.",
b: "Aplicar desinfetante diretamente sobre a sujeira visível para potencializar a ação química.",
c: "Substituir a limpeza úmida por varrição seca frequente nas áreas de circulação.",
d: "Utilizar pano seco com produto perfumado para reduzir odores e sensação de contaminação.",
e: "Aumentar a ventilação natural, mantendo a rotina de limpeza inalterada.",
correta: "a",
comentario: "A limpeza prévia com detergente remove matéria orgânica que reduz a eficácia do desinfetante. A desinfecção deve ocorrer após a limpeza física da superfície. Ministério da Saúde – Manual de Limpeza e Desinfecção: https://www.gov.br/saude"
},
{
id: "sim02",
materia: "Conhecimentos Específicos",
assunto: "Diluição de Produtos de Limpeza",
enunciado: "Um produto desinfetante recomenda diluição na proporção 1:50 para higienização de pisos. Considerando boas práticas de segurança e economia de recursos públicos, a conduta correta do agente de limpeza ao preparar a solução é:",
a: "Aumentar levemente a concentração para reforçar o poder germicida.",
b: "Seguir rigorosamente a proporção indicada pelo fabricante, utilizando medidor adequado.",
c: "Preparar solução concentrada e adicionar água conforme necessidade durante o uso.",
d: "Misturar o desinfetante com outro produto para ampliar o espectro de ação.",
e: "Diluir visualmente, tomando como referência a coloração da solução.",
correta: "b",
comentario: "A diluição deve obedecer às instruções do fabricante para garantir eficácia e segurança. Concentração inadequada pode reduzir ação ou causar riscos à saúde. ANVISA – Uso seguro de saneantes: https://www.gov.br/anvisa"
},
{
id: "sim03",
materia: "Conhecimentos Específicos",
assunto: "Coleta e Segregação de Resíduos",
enunciado: "Durante a rotina escolar, resíduos como papéis, restos alimentares e embalagens são descartados simultaneamente em salas de aula. Para atender às normas de gestão adequada de resíduos sólidos, o procedimento mais adequado é:",
a: "Encaminhar todos os resíduos para coleta urbana comum.",
b: "Acondicionar resíduos orgânicos e recicláveis em recipientes distintos e identificados.",
c: "Reunir resíduos recicláveis com orgânicos e separar posteriormente no depósito.",
d: "Priorizar o descarte rápido em detrimento da segregação inicial.",
e: "Destinar resíduos recicláveis diretamente ao aterro sanitário.",
correta: "b",
comentario: "A segregação deve ocorrer no momento da geração, utilizando recipientes identificados, conforme Política Nacional de Resíduos Sólidos (Lei 12.305/2010). https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/lei/l12305.htm"
},
{
id: "sim04",
materia: "Conhecimentos Específicos",
assunto: "Uso de EPIs",
enunciado: "Durante a limpeza de sanitários escolares, o servidor manipula produtos químicos e entra em contato com superfícies potencialmente contaminadas. Considerando normas de segurança no trabalho, é indispensável:",
a: "Utilizar apenas luvas descartáveis, devido à praticidade.",
b: "Realizar o procedimento com ventilação natural, dispensando proteção facial.",
c: "Utilizar luvas, avental impermeável e, quando necessário, proteção ocular.",
d: "Reduzir o uso de EPIs para preservar mobilidade.",
e: "Utilizar máscara simples somente quando houver odor forte.",
correta: "c",
comentario: "A NR-6 determina que o empregador forneça EPIs adequados ao risco, incluindo luvas, avental e proteção ocular quando houver exposição a agentes químicos ou biológicos. NR-6: https://www.gov.br/trabalho"
},
{
id: "sim05",
materia: "Conhecimentos Específicos",
assunto: "Cuidados com Pisos Escolares",
enunciado: "Em uma escola com pisos cerâmicos e áreas externas cimentadas, o agente de conservação deve adotar procedimentos diferenciados para evitar acidentes e danos estruturais. A prática mais adequada é:",
a: "Aplicar cera líquida em todos os tipos de piso para uniformizar o brilho.",
b: "Utilizar detergente neutro em pisos internos e jato controlado de água nas áreas externas.",
c: "Empregar escova metálica em cerâmica para remover manchas persistentes.",
d: "Lavar áreas internas com mangueira para agilizar o serviço.",
e: "Aplicar solução concentrada de desinfetante sem enxágue posterior.",
correta: "b",
comentario: "Cada tipo de piso exige técnica específica. Cerâmica requer detergente neutro; áreas externas podem receber lavagem com controle de pressão. Uso inadequado pode causar desgaste ou acidentes. Manual de Conservação Predial – FNDE: https://www.gov.br/fnde"
},
{
id: "sim06",
materia: "Conhecimentos Específicos",
assunto: "Prevenção de Acidentes",
enunciado: "Durante a limpeza de corredor interno em horário de intervalo, há intensa circulação de alunos. Para prevenir acidentes por escorregamento, o procedimento correto consiste em:",
a: "Isolar a área com sinalização adequada até a secagem completa.",
b: "Acelerar o processo utilizando maior volume de água.",
c: "Realizar a limpeza em etapas curtas, sem necessidade de aviso.",
d: "Solicitar que os alunos transitem com cuidado durante a atividade.",
e: "Optar por produto mais concentrado para reduzir o tempo de ação.",
correta: "a",
comentario: "A sinalização de piso molhado e isolamento da área reduzem riscos de queda, conforme normas de segurança ocupacional. NR-1 e boas práticas de prevenção de acidentes: https://www.gov.br/trabalho"
},
{
id: "sim07",
materia: "Conhecimentos Específicos",
assunto: "Saúde Pública no Ambiente Escolar",
enunciado: "Em períodos de aumento de casos de viroses, a equipe escolar reforça medidas preventivas. O agente de limpeza contribui de forma efetiva quando:",
a: "Prioriza áreas administrativas em detrimento das salas de aula.",
b: "Realiza desinfecção periódica de maçanetas, corrimãos e carteiras.",
c: "Substitui produtos desinfetantes por aromatizantes ambientais.",
d: "Reduz a frequência de limpeza para evitar exposição química.",
e: "Concentra esforços apenas nos sanitários.",
correta: "b",
comentario: "Superfícies de contato frequente são vetores de transmissão indireta. A desinfecção regular reduz disseminação de agentes infecciosos. Ministério da Saúde: https://www.gov.br/saude"
},
{
id: "sim08",
materia: "Conhecimentos Específicos",
assunto: "Economia de Recursos",
enunciado: "No contexto de responsabilidade socioambiental, a equipe de conservação deve adotar práticas que conciliem eficiência e economia. Uma conduta compatível com esse princípio é:",
a: "Manter torneiras abertas durante toda a lavagem para agilizar o processo.",
b: "Utilizar mangueira em fluxo contínuo para remoção de resíduos leves.",
c: "Substituir a limpeza úmida por varrição constante em todas as áreas.",
d: "Empregar balde com água controlada e reaproveitamento quando possível.",
e: "Priorizar produtos concentrados sem controle de diluição.",
correta: "d",
comentario: "O uso racional da água é medida de responsabilidade ambiental e econômica, evitando desperdício. Política Nacional de Educação Ambiental – Lei 9.795/1999: https://www.planalto.gov.br"
},
{
id: "sim09",
materia: "Conhecimentos Específicos",
assunto: "Atendimento e Comunicação",
enunciado: "Durante o expediente, um responsável questiona a interdição temporária de um sanitário para manutenção. A postura adequada do agente de limpeza, considerando ética e atendimento ao público, é:",
a: "Ignorar o questionamento por não ser atribuição administrativa.",
b: "Responder de forma técnica e objetiva, explicando o motivo da interdição.",
c: "Encaminhar o responsável diretamente à direção sem esclarecimento.",
d: "Autorizar o uso parcial para evitar reclamações.",
e: "Indicar que a decisão foi unilateral do servidor.",
correta: "b",
comentario: "A comunicação clara e respeitosa fortalece o serviço público e evita conflitos, mantendo transparência nas ações. Código de Ética do Servidor Público: https://www.planalto.gov.br"
},
{
id: "sim10",
materia: "Conhecimentos Específicos",
assunto: "Primeiros Socorros Básicos",
enunciado: "Ao presenciar queda de aluno em área recém-lavada, o agente de limpeza deve agir conforme princípios básicos de primeiros socorros até chegada de profissional habilitado. A conduta inicial correta é:",
a: "Movimentar o aluno imediatamente para local reservado.",
b: "Oferecer água e solicitar que retorne às atividades.",
c: "Avaliar nível de consciência e evitar movimentação brusca.",
d: "Aplicar pomada anti-inflamatória na área dolorida.",
e: "Permitir que colegas auxiliem na remoção do estudante.",
correta: "c",
comentario: "Nos primeiros socorros, deve-se avaliar consciência e evitar movimentação em caso de possível trauma, aguardando suporte adequado. Manual de Primeiros Socorros – Ministério da Saúde: https://www.gov.br/saude"
},
{
id: "sim11",
materia: "Conhecimentos Específicos",
assunto: "Limpeza de Áreas de Alimentação",
enunciado: "Durante a higienização do refeitório escolar após o intervalo, o agente identifica presença de resíduos orgânicos sob as mesas e próximo ao balcão de distribuição. Considerando normas sanitárias aplicáveis a áreas de manipulação e consumo de alimentos, a conduta mais adequada é:",
a: "Realizar varrição seca inicial e aplicar desinfetante diretamente sobre o piso.",
b: "Remover resíduos sólidos, lavar com detergente adequado e finalizar com desinfecção compatível com área alimentar.",
c: "Aplicar produto perfumado para neutralizar odores antes da limpeza úmida.",
d: "Lavar com jato de água pressurizada, direcionando resíduos ao ralo central.",
e: "Realizar limpeza parcial, priorizando apenas as áreas visivelmente sujas.",
correta: "b",
comentario: "Áreas de alimentação exigem limpeza seguida de desinfecção adequada, evitando contaminação cruzada. A RDC 216/2004 da ANVISA orienta sobre boas práticas em serviços de alimentação: https://www.gov.br/anvisa"
},
{
id: "sim12",
materia: "Conhecimentos Específicos",
assunto: "Manutenção Preventiva",
enunciado: "Em inspeção rotineira, o agente observa início de infiltração em parede próxima ao sanitário. Considerando o dever de preservação do patrimônio público, a medida mais adequada é:",
a: "Registrar a ocorrência e comunicar imediatamente ao setor responsável para providências.",
b: "Aplicar produto impermeabilizante superficial como solução temporária.",
c: "Ignorar a situação por não se tratar de atividade de limpeza.",
d: "Remover parcialmente o revestimento para verificar a extensão do dano.",
e: "Reduzir a frequência de lavagem da área para evitar agravamento.",
correta: "a",
comentario: "A comunicação formal de irregularidades integra a preservação do bem público e evita danos maiores. Princípios da administração pública – Art. 37 da Constituição: https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm"
},
{
id: "sim13",
materia: "Conhecimentos Específicos",
assunto: "Segurança no Uso de Produtos Químicos",
enunciado: "Durante o preparo de solução desengordurante, o agente percebe odor intenso e leve irritação ocular. À luz das normas de segurança, a conduta mais adequada é:",
a: "Prosseguir com o preparo reduzindo o tempo de exposição.",
b: "Misturar o produto com água adicional para diminuir o odor.",
c: "Interromper o preparo, reforçar ventilação e utilizar proteção adequada antes de retomar a atividade.",
d: "Transferir o produto para outro recipiente aberto.",
e: "Aplicar o produto imediatamente para evitar desperdício.",
correta: "c",
comentario: "Produtos químicos exigem ventilação adequada e uso de EPIs. A NR-6 e orientações da ANVISA tratam do uso seguro de saneantes: https://www.gov.br/anvisa"
},
{
id: "sim14",
materia: "Conhecimentos Específicos",
assunto: "Rotinas de Organização Escolar",
enunciado: "Em período de eventos escolares, o fluxo de pessoas aumenta significativamente. Para manter organização e segurança, o agente deve estruturar sua rotina considerando:",
a: "Priorização exclusiva das áreas administrativas.",
b: "Limpeza concentrada ao final do evento, evitando intervenções durante a circulação.",
c: "Acompanhamento contínuo das áreas críticas, com intervenções pontuais e sinalizadas.",
d: "Suspensão temporária das atividades de conservação externa.",
e: "Redução da frequência de coleta de resíduos para otimizar tempo.",
correta: "c",
comentario: "Ambientes com grande circulação exigem monitoramento constante e intervenções rápidas, prevenindo acidentes e acúmulo de resíduos. Manual de Segurança em Escolas – MEC: https://www.gov.br/mec"
},
{
id: "sim15",
materia: "Conhecimentos Específicos",
assunto: "Coleta Seletiva e Sustentabilidade",
enunciado: "A escola implementa programa de coleta seletiva envolvendo alunos e servidores. Para que o agente de limpeza contribua de forma técnica e alinhada à legislação, deve:",
a: "Unificar os resíduos ao final do turno para facilitar transporte.",
b: "Orientar a comunidade escolar quanto à separação correta e manter recipientes identificados.",
c: "Priorizar apenas resíduos recicláveis de maior valor comercial.",
d: "Armazenar resíduos orgânicos junto aos recicláveis até a coleta externa.",
e: "Descartar resíduos contaminados no mesmo recipiente dos recicláveis.",
correta: "b",
comentario: "A Política Nacional de Resíduos Sólidos prevê segregação na fonte e educação ambiental contínua. Lei 12.305/2010: https://www.planalto.gov.br"
},
{
id: "sim16",
materia: "Conhecimentos Específicos",
assunto: "Limpeza de Superfícies Diversas",
enunciado: "Carteiras escolares com superfícies laminadas apresentam manchas recorrentes de tinta. Considerando conservação do mobiliário e segurança, a conduta mais adequada é:",
a: "Utilizar solvente forte para remoção imediata da mancha.",
b: "Empregar esponja abrasiva para garantir retirada completa.",
c: "Aplicar produto compatível com o material, testando previamente em área discreta.",
d: "Raspar a superfície com lâmina metálica.",
e: "Cobrir a mancha com camada de cera líquida.",
correta: "c",
comentario: "A escolha do produto deve considerar o tipo de material, evitando danos permanentes. Manual de Conservação Predial – FNDE: https://www.gov.br/fnde"
},
{
id: "sim17",
materia: "Conhecimentos Específicos",
assunto: "Prevenção de Doenças Transmissíveis",
enunciado: "Em caso confirmado de doença contagiosa entre alunos, a equipe intensifica protocolos de higienização. A medida mais eficaz para reduzir transmissão indireta é:",
a: "Realizar desinfecção direcionada às superfícies de contato frequente com produto adequado.",
b: "Aplicar aromatizante ambiental nas salas afetadas.",
c: "Restringir limpeza apenas às áreas externas.",
d: "Aguardar orientação médica antes de qualquer procedimento.",
e: "Suspender temporariamente o uso de produtos químicos.",
correta: "a",
comentario: "Superfícies de contato são vetores importantes de transmissão. A desinfecção direcionada reduz risco de contágio. Ministério da Saúde – Prevenção de Doenças: https://www.gov.br/saude"
},
{
id: "sim18",
materia: "Conhecimentos Específicos",
assunto: "Ética no Serviço Público",
enunciado: "Durante a rotina de trabalho, o agente identifica material escolar deixado em sala após o expediente. Considerando ética e responsabilidade no serviço público, deve:",
a: "Levar o material para casa e devolvê-lo posteriormente.",
b: "Guardar o item em local seguro e comunicar à coordenação.",
c: "Ignorar o objeto por não ser atribuição direta.",
d: "Entregar o material a qualquer servidor disponível.",
e: "Descartar o item caso não seja identificado o proprietário.",
correta: "b",
comentario: "O servidor deve agir com zelo e responsabilidade sobre bens encontrados no ambiente público. Código de Ética do Servidor Público Federal: https://www.planalto.gov.br"
},
{
id: "sim19",
materia: "Conhecimentos Específicos",
assunto: "Uso Racional de Energia",
enunciado: "Durante a limpeza de salas no turno noturno, o agente observa iluminação total ativada, embora apenas parte do espaço esteja em uso. À luz da responsabilidade socioambiental, a conduta adequada é:",
a: "Manter todas as luzes acesas para agilizar a visualização.",
b: "Desligar pontos de iluminação não necessários durante a atividade.",
c: "Suspender a limpeza até o período diurno.",
d: "Solicitar substituição das lâmpadas por modelos mais potentes.",
e: "Manter iluminação integral para evitar acidentes.",
correta: "b",
comentario: "A economia de energia integra práticas de gestão responsável dos recursos públicos. Política Nacional de Eficiência Energética – Lei 10.295/2001: https://www.planalto.gov.br"
},
{
id: "sim20",
materia: "Conhecimentos Específicos",
assunto: "Trabalho em Equipe",
enunciado: "Em situação de acúmulo de demandas extraordinárias, a equipe de conservação reorganiza tarefas para atender prazos institucionais. A postura que demonstra colaboração e eficiência é:",
a: "Executar exclusivamente as atividades previamente designadas.",
b: "Compartilhar responsabilidades, respeitando limites de competência e segurança.",
c: "Transferir atividades mais complexas para servidores recém-ingressos.",
d: "Priorizar tarefas individuais em detrimento das coletivas.",
e: "Aguardar instrução formal para qualquer cooperação adicional.",
correta: "b",
comentario: "O trabalho em equipe fortalece a eficiência do serviço público e promove melhor distribuição das atividades. Princípios da Administração Pública – CF/88, art. 37: https://www.planalto.gov.br"
},
{
id: "sim21",
materia: "Conhecimentos Específicos",
assunto: "Limpeza de Sanitários Escolares",
enunciado: "Durante a higienização dos sanitários femininos, o agente observa acúmulo de biofilme em rejuntes e ralos. Considerando princípios de higiene, prevenção de odores e controle microbiológico, a conduta tecnicamente mais adequada é:",
a: "Aplicar desinfetante perfumado diretamente sobre as superfícies úmidas.",
b: "Realizar fricção mecânica com produto apropriado, seguida de enxágue e desinfecção.",
c: "Utilizar jato contínuo de água para deslocar resíduos aos ralos.",
d: "Reforçar apenas a aplicação de desodorizador ambiental.",
e: "Priorizar limpeza visual das áreas externas às cabines.",
correta: "b",
comentario: "Biofilmes exigem ação mecânica associada a produto adequado para remoção eficaz. A simples aplicação de desinfetante não elimina sujidade aderida. Manual de Limpeza e Desinfecção – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim22",
materia: "Conhecimentos Específicos",
assunto: "Armazenamento de Produtos de Limpeza",
enunciado: "Em vistoria interna, constatou-se que frascos de produtos químicos estavam armazenados sem identificação em prateleira de fácil acesso. Considerando normas de segurança, o procedimento correto é:",
a: "Manter os recipientes fechados e reorganizá-los por ordem alfabética.",
b: "Transferir os produtos para embalagens menores sem rotulagem para facilitar uso.",
c: "Armazenar em local ventilado, identificado e restrito, mantendo rótulos originais.",
d: "Guardar os produtos em armário compartilhado com materiais pedagógicos.",
e: "Diluir previamente todos os produtos antes de armazenar.",
correta: "c",
comentario: "Produtos químicos devem permanecer identificados, em local ventilado e restrito, conforme normas de segurança e orientações da ANVISA. https://www.gov.br/anvisa"
},
{
id: "sim23",
materia: "Conhecimentos Específicos",
assunto: "Conservação de Áreas Externas",
enunciado: "Após período chuvoso, áreas externas apresentam acúmulo de lama e folhas. Considerando segurança dos alunos e preservação do piso cimentado, a medida adequada é:",
a: "Remover resíduos sólidos e realizar lavagem controlada, evitando erosão da superfície.",
b: "Aplicar solução desinfetante concentrada para eliminar microrganismos.",
c: "Realizar apenas varrição superficial para manter aspecto visual.",
d: "Utilizar escova metálica para acelerar remoção de sujeira aderida.",
e: "Aguardar secagem natural antes de qualquer intervenção.",
correta: "a",
comentario: "A remoção física de resíduos seguida de lavagem controlada evita danos estruturais e riscos de queda. Manual de Conservação Predial – FNDE: https://www.gov.br/fnde"
},
{
id: "sim24",
materia: "Conhecimentos Específicos",
assunto: "Sinalização de Segurança",
enunciado: "Durante limpeza de escadaria interna, o agente precisa prevenir acidentes em área de circulação constante. À luz das normas de segurança no trabalho, deve:",
a: "Concluir a limpeza rapidamente, reduzindo tempo de exposição ao risco.",
b: "Solicitar apoio de servidor para orientar verbalmente os alunos.",
c: "Realizar limpeza parcial sem interrupção do fluxo.",
d: "Instalar sinalização visível e, se necessário, interditar temporariamente o acesso.",
e: "Utilizar produto de secagem rápida para evitar necessidade de aviso.",
correta: "d",
comentario: "A sinalização adequada é medida preventiva essencial para evitar quedas e acidentes. Normas de segurança ocupacional – NR-1: https://www.gov.br/trabalho"
},
{
id: "sim25",
materia: "Conhecimentos Específicos",
assunto: "Resíduos Potencialmente Contaminados",
enunciado: "Em sala de atendimento escolar, foram descartados lenços utilizados por aluno com sintomas gripais. Considerando princípios de biossegurança, o procedimento mais adequado é:",
a: "Recolher com luvas apropriadas e acondicionar em saco resistente, evitando contato direto.",
b: "Descartar junto ao lixo reciclável após varrição.",
c: "Comprimir o saco manualmente para reduzir volume.",
d: "Misturar aos resíduos comuns sem distinção.",
e: "Transportar sem utilização de recipiente fechado.",
correta: "a",
comentario: "Resíduos com potencial biológico devem ser manipulados com EPI e acondicionados adequadamente, reduzindo risco de contaminação. Ministério da Saúde – Biossegurança: https://www.gov.br/saude"
},
{
id: "sim26",
materia: "Conhecimentos Específicos",
assunto: "Preservação do Patrimônio Público",
enunciado: "Ao identificar carteira escolar com parafusos frouxos, oferecendo risco aos alunos, o agente deve:",
a: "Remover a carteira da sala e descartar imediatamente.",
b: "Registrar ocorrência e encaminhar para manutenção, evitando uso até reparo.",
c: "Realizar improviso com fita adesiva resistente.",
d: "Manter em uso até que ocorra dano mais evidente.",
e: "Transferir para outra sala menos utilizada.",
correta: "b",
comentario: "A preservação do patrimônio público inclui comunicação e retirada preventiva de item com risco estrutural. Constituição Federal, art. 37: https://www.planalto.gov.br"
},
{
id: "sim27",
materia: "Conhecimentos Específicos",
assunto: "Ventilação e Qualidade do Ar",
enunciado: "Durante limpeza com produto volátil em sala fechada, o agente deve considerar os impactos à saúde ocupacional. A conduta adequada é:",
a: "Reduzir a quantidade aplicada, mantendo ambiente fechado.",
b: "Realizar aplicação em horário de maior circulação para dispersão rápida.",
c: "Promover ventilação adequada antes, durante e após a aplicação.",
d: "Misturar o produto com essência aromática para suavizar odor.",
e: "Aplicar o produto em etapas prolongadas sem interrupção.",
correta: "c",
comentario: "Ambientes devem permanecer ventilados durante uso de produtos químicos, prevenindo intoxicação e irritações. NR-6 e orientações da ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim28",
materia: "Conhecimentos Específicos",
assunto: "Economia de Água",
enunciado: "Em procedimento de lavagem de pátio, visando eficiência e sustentabilidade, o agente deve:",
a: "Utilizar mangueira com fluxo contínuo para reduzir tempo de serviço.",
b: "Empregar balde e rodo, controlando volume de água utilizado.",
c: "Priorizar lavagem diária com grande volume de água.",
d: "Substituir limpeza úmida por desinfecção química concentrada.",
e: "Executar lavagem sem remoção prévia de resíduos sólidos.",
correta: "b",
comentario: "O uso controlado da água integra responsabilidade socioambiental e redução de desperdício. Lei 9.795/1999 – Educação Ambiental: https://www.planalto.gov.br"
},
{
id: "sim29",
materia: "Conhecimentos Específicos",
assunto: "Relações Interpessoais",
enunciado: "Durante conflito entre colegas de trabalho quanto à divisão de tarefas, o agente demonstra postura profissional adequada quando:",
a: "Recusa diálogo até definição formal da chefia.",
b: "Expõe o conflito diante de alunos para buscar apoio.",
c: "Reorganiza unilateralmente as tarefas.",
d: "Solicita mediação respeitosa, buscando solução cooperativa.",
e: "Executa apenas parte das atividades designadas.",
correta: "d",
comentario: "A resolução dialogada de conflitos fortalece o trabalho em equipe e o ambiente institucional. Princípios da administração pública – CF/88: https://www.planalto.gov.br"
},
{
id: "sim30",
materia: "Conhecimentos Específicos",
assunto: "Inclusão e Respeito às Diferenças",
enunciado: "Em ambiente escolar inclusivo, o agente de limpeza deve organizar espaços considerando acessibilidade e segurança de alunos com deficiência. A prática adequada é:",
a: "Manter equipamentos e materiais fora das rotas de circulação acessível.",
b: "Priorizar limpeza apenas das áreas centrais do prédio.",
c: "Reduzir mobiliário para ampliar espaço de circulação.",
d: "Realizar intervenções sem considerar sinalização tátil.",
e: "Alterar disposição dos móveis sem comunicação prévia.",
correta: "a",
comentario: "Ambientes inclusivos exigem manutenção das rotas acessíveis livres de obstáculos, conforme Estatuto da Pessoa com Deficiência – Lei 13.146/2015: https://www.planalto.gov.br"
},
{
id: "sim31",
materia: "Conhecimentos Específicos",
assunto: "Desinfecção de Superfícies de Alto Contato",
enunciado: "Em escola com grande circulação diária, maçanetas, corrimãos e interruptores são considerados pontos críticos de contaminação indireta. Considerando princípios de assepsia e controle epidemiológico, a prática mais adequada é:",
a: "Realizar apenas limpeza visual diária com pano seco.",
b: "Aplicar desinfetante após limpeza prévia, respeitando tempo de contato indicado pelo fabricante.",
c: "Substituir desinfecção por ventilação constante dos ambientes.",
d: "Utilizar produto aromatizante com ação bacteriostática.",
e: "Desinfetar apenas quando houver casos confirmados de doença.",
correta: "b",
comentario: "A desinfecção eficaz depende de limpeza prévia e respeito ao tempo de contato do produto, conforme orientações técnicas da ANVISA. https://www.gov.br/anvisa"
},
{
id: "sim32",
materia: "Conhecimentos Específicos",
assunto: "Mistura de Produtos Químicos",
enunciado: "Durante a rotina, um servidor sugere misturar desinfetante com água sanitária para ampliar a eficácia da limpeza. Considerando normas de segurança química, a conduta adequada é:",
a: "Realizar a mistura em pequena quantidade para testar reação.",
b: "Misturar os produtos em ambiente ventilado.",
c: "Seguir a sugestão caso o odor não seja intenso.",
d: "Evitar mistura de produtos químicos sem orientação técnica do fabricante.",
e: "Diluir ambos em maior volume de água antes da mistura.",
correta: "d",
comentario: "A mistura de produtos pode gerar gases tóxicos ou reações perigosas. Deve-se seguir estritamente instruções do fabricante. Orientações de segurança – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim33",
materia: "Conhecimentos Específicos",
assunto: "Limpeza de Vidros e Janelas",
enunciado: "Ao realizar limpeza de janelas em pavimento superior, o agente deve considerar riscos de queda e integridade estrutural. A prática tecnicamente correta é:",
a: "Apoiar-se parcialmente na estrutura externa para alcançar áreas mais altas.",
b: "Utilizar equipamento adequado e, se necessário, solicitar apoio para garantir estabilidade.",
c: "Realizar a limpeza inclinando o corpo além do limite da janela.",
d: "Executar a atividade durante intervalo escolar para evitar interrupções.",
e: "Aplicar grande volume de produto para reduzir necessidade de fricção.",
correta: "b",
comentario: "Atividades em altura exigem medidas preventivas e equipamentos adequados, conforme normas de segurança no trabalho. NR-35: https://www.gov.br/trabalho"
},
{
id: "sim34",
materia: "Conhecimentos Específicos",
assunto: "Controle de Pragas",
enunciado: "Ao identificar presença recorrente de insetos em área de armazenamento de alimentos, o agente deve adotar medida inicial compatível com boas práticas sanitárias:",
a: "Aplicar inseticida doméstico sem comunicação prévia.",
b: "Armazenar alimentos em recipientes abertos para monitoramento.",
c: "Comunicar à gestão para adoção de controle integrado e reforçar higiene do local.",
d: "Reduzir frequência de limpeza para evitar dispersão.",
e: "Manter resíduos orgânicos próximos para atrair insetos e facilitar eliminação.",
correta: "c",
comentario: "O controle integrado de pragas exige comunicação formal e medidas estruturais, não apenas aplicação isolada de inseticida. RDC 216/2004 – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim35",
materia: "Conhecimentos Específicos",
assunto: "Organização de Depósito de Materiais",
enunciado: "No depósito da escola, produtos e equipamentos encontram-se armazenados sem critério técnico. Considerando segurança e eficiência operacional, a medida adequada é:",
a: "Organizar por frequência de uso e risco químico, mantendo identificação visível.",
b: "Agrupar todos os líquidos em mesma prateleira.",
c: "Armazenar materiais pesados em prateleiras superiores.",
d: "Manter produtos abertos para facilitar acesso.",
e: "Separar produtos apenas por cor da embalagem.",
correta: "a",
comentario: "A organização deve considerar risco químico, ergonomia e identificação adequada, prevenindo acidentes e desperdícios. NR-6 e boas práticas de armazenamento: https://www.gov.br/trabalho"
},
{
id: "sim36",
materia: "Conhecimentos Específicos",
assunto: "Ergonomia no Trabalho",
enunciado: "Durante varrição prolongada de pátio, o agente sente desconforto lombar recorrente. À luz de princípios ergonômicos, a medida preventiva mais adequada é:",
a: "Reduzir o ritmo da atividade mantendo postura habitual.",
b: "Alternar tarefas e ajustar postura e altura do equipamento utilizado.",
c: "Aumentar força aplicada para concluir mais rapidamente.",
d: "Realizar pausas somente ao final do turno.",
e: "Ignorar o desconforto até avaliação médica posterior.",
correta: "b",
comentario: "A NR-17 trata da ergonomia, recomendando adequação de postura e alternância de tarefas para evitar lesões. https://www.gov.br/trabalho"
},
{
id: "sim37",
materia: "Conhecimentos Específicos",
assunto: "Descarte de Perfurocortantes",
enunciado: "Durante limpeza de sala de atendimento, o agente encontra objeto perfurocortante descartado inadequadamente. Considerando biossegurança, deve:",
a: "Recolher manualmente com luva comum e descartar em saco plástico.",
b: "Quebrar o objeto antes do descarte para reduzir risco.",
c: "Acondicionar em recipiente rígido apropriado e comunicar ocorrência.",
d: "Encaminhar diretamente ao lixo comum fechado.",
e: "Envolver em papel grosso e descartar junto aos recicláveis.",
correta: "c",
comentario: "Perfurocortantes exigem acondicionamento em recipiente rígido e comunicação formal para evitar acidentes. Ministério da Saúde – Biossegurança: https://www.gov.br/saude"
},
{
id: "sim38",
materia: "Conhecimentos Específicos",
assunto: "Limpeza Pós-Evento Escolar",
enunciado: "Após evento com grande público, há acúmulo significativo de resíduos diversos. Para restaurar condições adequadas de uso, o agente deve:",
a: "Priorizar apenas remoção visual dos resíduos maiores.",
b: "Executar coleta seletiva inicial, seguida de limpeza e desinfecção das áreas críticas.",
c: "Realizar varrição rápida e liberar o espaço imediatamente.",
d: "Aplicar desinfetante antes da remoção dos resíduos sólidos.",
e: "Concentrar esforços apenas nas áreas internas.",
correta: "b",
comentario: "A sequência técnica adequada é coleta, limpeza e posterior desinfecção, garantindo segurança sanitária. Política Nacional de Resíduos Sólidos: https://www.planalto.gov.br"
},
{
id: "sim39",
materia: "Conhecimentos Específicos",
assunto: "Comunicação Institucional",
enunciado: "Ao perceber risco potencial em estrutura provisória montada para atividade escolar, o agente deve:",
a: "Aguardar manifestação da equipe organizadora.",
b: "Intervir diretamente desmontando a estrutura.",
c: "Alertar informalmente alunos próximos.",
d: "Registrar e comunicar imediatamente à autoridade competente.",
e: "Ignorar a situação por não ser responsável pela montagem.",
correta: "d",
comentario: "A comunicação formal de risco integra dever funcional e prevenção de acidentes no serviço público. Art. 37 da Constituição Federal: https://www.planalto.gov.br"
},
{
id: "sim40",
materia: "Conhecimentos Específicos",
assunto: "Rotina de Limpeza Planejada",
enunciado: "Para garantir eficiência e padronização dos serviços de conservação escolar, a rotina de limpeza deve ser estruturada considerando:",
a: "Execução das tarefas conforme demanda eventual.",
b: "Planejamento prévio com cronograma definido e registro das atividades realizadas.",
c: "Prioridade exclusiva às áreas visíveis ao público externo.",
d: "Substituição de registros formais por comunicação verbal.",
e: "Reorganização diária sem critério fixo.",
correta: "b",
comentario: "O planejamento e registro das atividades garantem controle, eficiência e transparência no serviço público. Princípios administrativos – CF/88: https://www.planalto.gov.br"
},
{
id: "sim41",
materia: "Conhecimentos Específicos",
assunto: "Limpeza Terminal em Ambiente Escolar",
enunciado: "Após período de recesso escolar, a direção determina limpeza completa das salas antes do retorno das aulas. Considerando conceitos técnicos, a limpeza terminal caracteriza-se por:",
a: "Procedimento superficial realizado apenas em áreas visíveis.",
b: "Aumento da frequência da varrição seca nos corredores.",
c: "Higienização minuciosa de todas as superfícies, mobiliários e pontos de contato, incluindo áreas menos acessíveis.",
d: "Aplicação exclusiva de desodorizadores ambientais.",
e: "Restrição da limpeza aos sanitários e áreas administrativas.",
correta: "c",
comentario: "Limpeza terminal envolve higienização completa e detalhada do ambiente, incluindo superfícies pouco acessíveis, garantindo segurança sanitária antes da ocupação. Manual de Limpeza e Desinfecção – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim42",
materia: "Conhecimentos Específicos",
assunto: "Riscos Biológicos",
enunciado: "Durante a coleta de resíduos em enfermaria escolar, o agente identifica materiais com vestígios de fluidos corporais. Considerando normas de biossegurança, a conduta adequada é:",
a: "Acondicionar em recipiente resistente, utilizando EPI apropriado e evitando compactação manual.",
b: "Descartar junto ao lixo comum em saco reforçado.",
c: "Lavar os resíduos antes do descarte.",
d: "Transportar manualmente até a área externa sem recipiente fechado.",
e: "Separar apenas materiais perfurocortantes, mantendo os demais no lixo comum.",
correta: "a",
comentario: "Resíduos com possível contaminação biológica exigem acondicionamento adequado e uso de EPIs, prevenindo exposição ocupacional. Ministério da Saúde – Biossegurança: https://www.gov.br/saude"
},
{
id: "sim43",
materia: "Conhecimentos Específicos",
assunto: "Manuseio de Equipamentos Elétricos",
enunciado: "Ao utilizar enceradeira elétrica em piso interno, o agente deve adotar medidas preventivas relacionadas à segurança elétrica. A prática correta é:",
a: "Utilizar extensão improvisada para alcançar maior área.",
b: "Operar o equipamento com mãos úmidas, desde que usando luvas.",
c: "Verificar integridade do cabo e evitar contato do fio com áreas molhadas.",
d: "Posicionar o cabo sob a máquina para facilitar deslocamento.",
e: "Realizar manutenção preventiva apenas quando ocorrer falha.",
correta: "c",
comentario: "Equipamentos elétricos exigem verificação prévia de cabos e prevenção de contato com água, evitando risco de choque elétrico. NR-10 – Segurança em Instalações Elétricas: https://www.gov.br/trabalho"
},
{
id: "sim44",
materia: "Conhecimentos Específicos",
assunto: "Controle de Odores em Sanitários",
enunciado: "Mesmo após limpeza diária, sanitários apresentam odores persistentes. Considerando abordagem técnica, a medida mais eficaz é:",
a: "Intensificar uso de aromatizantes.",
b: "Aplicar desinfetante concentrado sem remoção prévia de resíduos.",
c: "Investigar possível falha na vedação de ralos e reforçar limpeza dos sifões.",
d: "Reduzir uso de água para evitar umidade.",
e: "Realizar limpeza apenas no início do turno.",
correta: "c",
comentario: "Odores persistentes podem estar relacionados a falhas estruturais ou acúmulo em sifões. A solução exige análise da causa e não apenas mascaramento. Manual de Saneamento Básico – FUNASA: https://www.gov.br/funasa"
},
{
id: "sim45",
materia: "Conhecimentos Específicos",
assunto: "Prevenção de Quedas",
enunciado: "Em dias chuvosos, o piso da entrada principal torna-se escorregadio devido ao fluxo intenso de pessoas. Para prevenir acidentes, o agente deve:",
a: "Aplicar cera antiderrapante imediatamente após a chuva.",
b: "Instalar tapetes absorventes e reforçar sinalização preventiva.",
c: "Realizar lavagem contínua para remover marcas de sapatos.",
d: "Reduzir a frequência de limpeza para evitar umidade.",
e: "Isolar permanentemente a entrada principal.",
correta: "b",
comentario: "Tapetes absorventes e sinalização reduzem risco de quedas em períodos chuvosos, mantendo segurança sem interromper circulação. NR-1 – Prevenção de Riscos: https://www.gov.br/trabalho"
},
{
id: "sim46",
materia: "Conhecimentos Específicos",
assunto: "Separação de Resíduos Recicláveis",
enunciado: "Ao organizar a coleta seletiva, o agente identifica mistura de papel com resíduos orgânicos. Considerando eficiência do processo, deve:",
a: "Encaminhar todo o conteúdo ao lixo comum.",
b: "Separar manualmente utilizando luvas e acondicionar corretamente cada tipo.",
c: "Compactar o material para reduzir volume.",
d: "Descartar os recicláveis contaminados em recipiente de vidro.",
e: "Manter mistura até a coleta externa.",
correta: "b",
comentario: "A segregação adequada na fonte aumenta eficiência da reciclagem e reduz contaminação do material reaproveitável. Lei 12.305/2010 – Política Nacional de Resíduos Sólidos: https://www.planalto.gov.br"
},
{
id: "sim47",
materia: "Conhecimentos Específicos",
assunto: "Organização de Rotas de Limpeza",
enunciado: "Para otimizar tempo e reduzir retrabalho, a definição de rotas de limpeza deve considerar:",
a: "Execução aleatória das atividades conforme disponibilidade.",
b: "Ordem que evite retorno a áreas já higienizadas e respeite fluxo de circulação.",
c: "Prioridade exclusiva às áreas externas.",
d: "Limpeza simultânea de ambientes opostos sem critério.",
e: "Início pelas áreas administrativas independentemente da demanda.",
correta: "b",
comentario: "Planejamento de rotas evita retrabalho e contaminação cruzada, aumentando eficiência operacional. Princípios de gestão pública – CF/88: https://www.planalto.gov.br"
},
{
id: "sim48",
materia: "Conhecimentos Específicos",
assunto: "Primeiros Socorros em Caso de Corte",
enunciado: "Durante a coleta de resíduos, o agente sofre pequeno corte superficial. A conduta inicial adequada é:",
a: "Continuar a atividade e higienizar ao final do turno.",
b: "Aplicar produto químico de limpeza diretamente sobre o ferimento.",
c: "Lavar com água corrente, realizar assepsia e comunicar a ocorrência.",
d: "Cobrir o ferimento com papel absorvente.",
e: "Ignorar o ferimento caso não haja dor intensa.",
correta: "c",
comentario: "Pequenos cortes exigem lavagem imediata, assepsia e comunicação formal, prevenindo infecções e registro de acidente. Manual de Primeiros Socorros – Ministério da Saúde: https://www.gov.br/saude"
},
{
id: "sim49",
materia: "Conhecimentos Específicos",
assunto: "Conservação de Mobiliário",
enunciado: "Durante limpeza de armários de madeira, o agente deve considerar características do material para evitar danos. A conduta correta é:",
a: "Aplicar água em abundância para remover poeira acumulada.",
b: "Utilizar produto compatível com madeira e pano levemente umedecido.",
c: "Empregar escova metálica para remover manchas.",
d: "Aplicar desinfetante concentrado sem enxágue.",
e: "Utilizar jato pressurizado para alcançar cantos internos.",
correta: "b",
comentario: "Madeira exige produto adequado e controle de umidade para evitar deformações e danos estruturais. Manual de Conservação Predial – FNDE: https://www.gov.br/fnde"
},
{
id: "sim50",
materia: "Conhecimentos Específicos",
assunto: "Responsabilidade Funcional",
enunciado: "Ao perceber desperdício recorrente de materiais de limpeza por uso inadequado, o agente deve:",
a: "Ignorar a situação por não envolver sua atividade direta.",
b: "Reduzir estoque sem comunicar à gestão.",
c: "Comunicar formalmente e sugerir orientação técnica à equipe.",
d: "Restringir acesso aos produtos sem autorização.",
e: "Substituir os produtos por outros de menor qualidade.",
correta: "c",
comentario: "A responsabilidade funcional inclui zelar pelo uso racional de recursos públicos e comunicar irregularidades. Art. 37 da Constituição Federal: https://www.planalto.gov.br"
},
{
id: "sim51",
materia: "Conhecimentos Específicos",
assunto: "Diluição Correta de Água Sanitária",
enunciado: "Para desinfecção de superfícies potencialmente contaminadas, a água sanitária deve ser diluída conforme orientação do fabricante. Considerando segurança, eficácia e preservação das superfícies escolares, a conduta adequada é:",
a: "Utilizar concentração superior à indicada para ampliar poder germicida.",
b: "Preparar solução conforme proporção recomendada e utilizar dentro do prazo de validade da diluição.",
c: "Armazenar solução diluída por tempo indeterminado em recipiente aberto.",
d: "Misturar com detergente para potencializar ação desinfetante.",
e: "Aplicar diretamente na superfície sem limpeza prévia.",
correta: "b",
comentario: "A eficácia da água sanitária depende da diluição correta e do uso em período adequado após preparo. Misturas indevidas reduzem segurança e eficácia. Orientações técnicas – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim52",
materia: "Conhecimentos Específicos",
assunto: "Limpeza de Quadra Esportiva",
enunciado: "Após atividade física intensa, a quadra apresenta resíduos de suor, poeira e marcas de calçados. Considerando segurança dos usuários e conservação do piso, a prática adequada é:",
a: "Aplicar cera líquida para uniformizar o brilho.",
b: "Realizar apenas varrição seca diária.",
c: "Utilizar escova metálica para remoção das marcas.",
d: "Lavar com mangueira de alta pressão independentemente do tipo de piso.",
e: "Executar limpeza úmida com produto compatível e secagem adequada para evitar escorregamento.",
correta: "e",
comentario: "Quadras exigem limpeza úmida controlada com produto adequado ao tipo de piso, evitando desgaste e riscos de queda. Manual de Conservação Predial – FNDE: https://www.gov.br/fnde"
},
{
id: "sim53",
materia: "Conhecimentos Específicos",
assunto: "Acondicionamento de Lixo",
enunciado: "Durante o recolhimento diário, o agente identifica sacos de lixo excessivamente cheios e mal fechados. Para prevenir acidentes e contaminação, a medida adequada é:",
a: "Compactar manualmente para reduzir volume antes do transporte.",
b: "Transportar mesmo sem fechamento adequado para evitar atraso.",
c: "Reforçar o fechamento e, se necessário, redistribuir o conteúdo em novos sacos resistentes.",
d: "Misturar com resíduos recicláveis para diminuir peso.",
e: "Deixar para coleta externa resolver o excesso de volume.",
correta: "c",
comentario: "O acondicionamento correto previne rompimento do saco, exposição a resíduos e acidentes ocupacionais. Política Nacional de Resíduos Sólidos – Lei 12.305/2010: https://www.planalto.gov.br"
},
{
id: "sim54",
materia: "Conhecimentos Específicos",
assunto: "Uso Correto de EPIs",
enunciado: "Ao realizar limpeza com produto desengordurante alcalino, o agente deve utilizar EPIs adequados ao risco químico. A prática correta é:",
a: "Utilizar apenas máscara simples de tecido.",
b: "Substituir luvas por lavagem frequente das mãos.",
c: "Usar luvas impermeáveis, proteção ocular e avental apropriado.",
d: "Aplicar o produto rapidamente para reduzir exposição.",
e: "Utilizar EPI apenas se houver odor forte.",
correta: "c",
comentario: "Produtos alcalinos podem causar irritação cutânea e ocular, exigindo uso de EPIs compatíveis conforme NR-6. https://www.gov.br/trabalho"
},
{
id: "sim55",
materia: "Conhecimentos Específicos",
assunto: "Comunicação de Riscos",
enunciado: "Ao identificar fiação elétrica exposta em área comum da escola, o agente deve agir conforme princípios de prevenção e responsabilidade funcional. A conduta adequada é:",
a: "Isolar provisoriamente com fita adesiva comum.",
b: "Evitar circulação próxima e comunicar imediatamente ao setor competente.",
c: "Ignorar, pois não integra atividade de limpeza.",
d: "Desligar o disjuntor geral sem autorização.",
e: "Cobrir com pano para evitar contato visual.",
correta: "b",
comentario: "Fiação exposta representa risco grave e deve ser comunicada imediatamente para reparo adequado. NR-10 – Segurança em Instalações Elétricas: https://www.gov.br/trabalho"
},
{
id: "sim56",
materia: "Conhecimentos Específicos",
assunto: "Organização de Materiais de Limpeza",
enunciado: "Para evitar contaminação cruzada, o agente deve organizar panos e utensílios de limpeza considerando:",
a: "Uso indistinto para sanitários e salas de aula.",
b: "Separação por cores ou identificação conforme área de utilização.",
c: "Armazenamento conjunto após lavagem simples.",
d: "Utilização alternada entre ambientes sem critério.",
e: "Substituição apenas quando houver desgaste visível.",
correta: "b",
comentario: "A separação por cores reduz risco de contaminação cruzada entre ambientes distintos, especialmente sanitários e áreas comuns. Manual de Limpeza – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim57",
materia: "Conhecimentos Específicos",
assunto: "Economia de Materiais",
enunciado: "Para garantir uso racional de detergente líquido, o agente deve:",
a: "Aplicar diretamente no piso em grande quantidade.",
b: "Diluir conforme orientação técnica e utilizar medidor adequado.",
c: "Misturar com outros produtos para ampliar rendimento.",
d: "Aumentar concentração em períodos de maior sujeira.",
e: "Reaproveitar solução contaminada em diferentes ambientes.",
correta: "b",
comentario: "A dosagem correta evita desperdício e mantém eficácia do produto, promovendo gestão responsável de recursos públicos. Orientações técnicas – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim58",
materia: "Conhecimentos Específicos",
assunto: "Limpeza de Equipamentos Compartilhados",
enunciado: "Computadores de uso coletivo apresentam acúmulo de poeira e marcas de uso. Considerando preservação do equipamento e segurança elétrica, a prática correta é:",
a: "Aplicar solução líquida diretamente sobre o teclado.",
b: "Utilizar pano levemente umedecido e produto adequado, evitando excesso de líquido.",
c: "Lavar componentes removíveis em água corrente.",
d: "Utilizar jato de ar comprimido improvisado com mangueira.",
e: "Desligar o equipamento apenas após a limpeza.",
correta: "b",
comentario: "Equipamentos eletrônicos exigem cuidado com umidade e produtos específicos para evitar danos e risco elétrico. NR-10: https://www.gov.br/trabalho"
},
{
id: "sim59",
materia: "Conhecimentos Específicos",
assunto: "Prevenção de Incêndios",
enunciado: "Ao armazenar produtos inflamáveis utilizados na limpeza, o agente deve considerar medidas de prevenção contra incêndio. A prática adequada é:",
a: "Armazenar próximo a fontes de calor para facilitar acesso.",
b: "Guardar em local ventilado, afastado de fontes de ignição e devidamente identificado.",
c: "Manter recipientes abertos para evitar pressão interna.",
d: "Misturar com produtos não inflamáveis para reduzir risco.",
e: "Armazenar em qualquer armário disponível.",
correta: "b",
comentario: "Produtos inflamáveis devem ser armazenados em local ventilado e longe de fontes de calor, prevenindo incêndios. Normas de segurança do trabalho – NR-23: https://www.gov.br/trabalho"
},
{
id: "sim60",
materia: "Conhecimentos Específicos",
assunto: "Postura Profissional no Ambiente Escolar",
enunciado: "Durante atendimento a aluno que questiona procedimento de limpeza em andamento, o agente demonstra postura profissional adequada quando:",
a: "Responde de forma objetiva e respeitosa, esclarecendo a necessidade da atividade.",
b: "Ignora o questionamento para manter foco exclusivo na tarefa.",
c: "Interrompe a atividade e abandona o procedimento.",
d: "Reage de forma ríspida diante da interrupção.",
e: "Encaminha o aluno a outro servidor sem explicação.",
correta: "a",
comentario: "A postura ética e respeitosa fortalece o ambiente escolar e está alinhada aos princípios do serviço público. Constituição Federal, art. 37: https://www.planalto.gov.br"
},
{
id: "sim61",
materia: "Conhecimentos Específicos",
assunto: "Lavagem de Pisos Internos",
enunciado: "Durante a lavagem de piso cerâmico em corredor interno, o agente deve evitar riscos de infiltração e acidentes. Considerando técnica adequada e segurança dos usuários, a conduta correta é:",
a: "Utilizar grande volume de água para acelerar remoção da sujeira.",
b: "Aplicar detergente concentrado sem diluição prévia.",
c: "Realizar limpeza com pano ou mop úmido, controlando a quantidade de água e sinalizando a área.",
d: "Executar lavagem durante o intervalo com circulação parcial.",
e: "Dispensar enxágue quando o produto não apresentar espuma visível.",
correta: "c",
comentario: "O controle da umidade e a sinalização da área são essenciais para evitar infiltrações e quedas. A técnica de limpeza úmida reduz riscos estruturais e ocupacionais. Manual de Conservação Predial – FNDE: https://www.gov.br/fnde"
},
{
id: "sim62",
materia: "Conhecimentos Específicos",
assunto: "Controle de Contaminação Cruzada",
enunciado: "Ao finalizar limpeza de sanitário e iniciar atividade em sala de aula, o agente deve adotar medida preventiva para evitar contaminação cruzada entre ambientes distintos:",
a: "Utilizar os mesmos utensílios após enxágue simples.",
b: "Substituir ou higienizar adequadamente os utensílios antes de utilizá-los em outro ambiente.",
c: "Aplicar desinfetante mais concentrado na sala de aula.",
d: "Reduzir tempo de limpeza na segunda área.",
e: "Executar varrição seca como medida suficiente.",
correta: "b",
comentario: "A troca ou higienização dos utensílios evita transferência de microrganismos entre ambientes com diferentes níveis de risco. Orientações técnicas – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim63",
materia: "Conhecimentos Específicos",
assunto: "Manutenção Preventiva Simples",
enunciado: "Durante inspeção rotineira, o agente identifica torneira com vazamento contínuo em bebedouro escolar. Considerando responsabilidade funcional e economia de recursos, deve:",
a: "Aguardar manutenção periódica programada.",
b: "Ignorar, pois não integra suas atribuições diretas.",
c: "Fechar registro, se possível, e comunicar imediatamente ao setor responsável.",
d: "Colocar recipiente para coletar a água até solução definitiva.",
e: "Reduzir frequência de limpeza do local.",
correta: "c",
comentario: "O vazamento implica desperdício de água e deve ser comunicado prontamente, podendo o agente adotar medida preventiva inicial segura. Lei 9.795/1999 – Educação Ambiental: https://www.planalto.gov.br"
},
{
id: "sim64",
materia: "Conhecimentos Específicos",
assunto: "Armazenamento de Resíduos",
enunciado: "Após coleta interna, os resíduos permanecem temporariamente armazenados até recolhimento externo. Considerando normas sanitárias, o local adequado deve ser:",
a: "Área ventilada, protegida de intempéries e com acesso restrito.",
b: "Espaço aberto próximo à entrada principal.",
c: "Ambiente compartilhado com depósito de alimentos.",
d: "Corredor de circulação pouco utilizado.",
e: "Qualquer local externo disponível.",
correta: "a",
comentario: "O armazenamento temporário deve evitar exposição ao público, animais e intempéries, mantendo condições sanitárias adequadas. Política Nacional de Resíduos Sólidos – Lei 12.305/2010: https://www.planalto.gov.br"
},
{
id: "sim65",
materia: "Conhecimentos Específicos",
assunto: "Uso de Escadas Portáteis",
enunciado: "Ao utilizar escada portátil para alcançar luminária em sala de aula, o agente deve observar medidas de segurança que incluam:",
a: "Posicionar a escada sobre superfície estável e manter três pontos de apoio durante a atividade.",
b: "Apoiar a escada parcialmente em mobiliário próximo.",
c: "Subir com materiais soltos nas mãos.",
d: "Estender o corpo lateralmente para alcançar área distante.",
e: "Executar a tarefa sozinho em ambiente fechado.",
correta: "a",
comentario: "A estabilidade da escada e manutenção de três pontos de apoio reduzem significativamente risco de queda. Normas de segurança no trabalho – NR-35: https://www.gov.br/trabalho"
},
{
id: "sim66",
materia: "Conhecimentos Específicos",
assunto: "Limpeza de Refeitório Escolar",
enunciado: "Após distribuição de merenda, mesas apresentam resíduos líquidos e sólidos. Considerando segurança alimentar e higiene coletiva, a conduta adequada é:",
a: "Realizar apenas varrição seca para agilizar liberação do espaço.",
b: "Remover resíduos sólidos, proceder à limpeza com detergente e finalizar com desinfecção compatível com área de alimentação.",
c: "Aplicar aromatizante diretamente sobre as mesas.",
d: "Lavar mesas com grande volume de água corrente.",
e: "Aguardar secagem natural dos resíduos antes da limpeza.",
correta: "b",
comentario: "Ambientes de alimentação exigem sequência técnica: remoção de resíduos, limpeza com detergente e posterior desinfecção. RDC 216/2004 – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim67",
materia: "Conhecimentos Específicos",
assunto: "Prevenção de Intoxicação Química",
enunciado: "Durante preparo de solução, o agente percebe ausência de rótulo no recipiente. Para prevenir intoxicação ou uso incorreto, deve:",
a: "Testar pequena quantidade para identificar o produto.",
b: "Utilizar conforme experiência anterior.",
c: "Descartar imediatamente no ralo.",
d: "Transferir para frasco identificado provisoriamente.",
e: "Não utilizar o produto até que seja devidamente identificado.",
correta: "e",
comentario: "Produtos sem identificação não devem ser utilizados, pois representam risco químico significativo. Normas de segurança química – ANVISA: https://www.gov.br/anvisa"
},
{
id: "sim68",
materia: "Conhecimentos Específicos",
assunto: "Organização de Espaços Escolares",
enunciado: "Após reorganização de mobiliário para evento, o agente deve garantir que:",
a: "Os móveis permaneçam conforme disposição temporária.",
b: "As rotas de fuga e circulação estejam livres e sinalizadas.",
c: "Os corredores sejam parcialmente ocupados para otimização do espaço.",
d: "A disposição priorize estética em detrimento da segurança.",
e: "O retorno ao layout original ocorra apenas se solicitado formalmente.",
correta: "b",
comentario: "A manutenção de rotas de fuga desobstruídas é requisito essencial de segurança contra incêndio e evacuação. NR-23 – Proteção Contra Incêndios: https://www.gov.br/trabalho"
},
{
id: "sim69",
materia: "Conhecimentos Específicos",
assunto: "Cooperação no Ambiente Escolar",
enunciado: "Durante situação emergencial que exige evacuação do prédio, o agente de limpeza deve:",
a: "Priorizar guarda de equipamentos antes de deixar o local.",
b: "Aguardar orientação exclusiva da chefia imediata.",
c: "Auxiliar na orientação das pessoas próximas, mantendo calma e seguindo o plano de evacuação.",
d: "Retornar ao depósito para desligar todos os equipamentos.",
e: "Interromper comunicação para evitar pânico.",
correta: "c",
comentario: "Em emergências, todos os servidores devem colaborar com o plano de evacuação, priorizando segurança das pessoas. NR-23 – Proteção Contra Incêndios: https://www.gov.br/trabalho"
},
{
id: "sim70",
materia: "Conhecimentos Específicos",
assunto: "Gestão Sustentável de Recursos",
enunciado: "Para reduzir impactos ambientais da atividade de limpeza escolar, o agente deve adotar prática que envolva:",
a: "Uso indiscriminado de produtos concentrados.",
b: "Diluição correta, controle de consumo e preferência por produtos autorizados pelos órgãos competentes.",
c: "Lavagem diária de todas as áreas externas com mangueira.",
d: "Descarte conjunto de resíduos recicláveis e orgânicos.",
e: "Substituição de limpeza úmida por aplicação constante de desinfetantes.",
correta: "b",
comentario: "A gestão sustentável envolve uso racional de produtos e respeito às normas ambientais, promovendo eficiência e responsabilidade socioambiental. Lei 9.795/1999 – Educação Ambiental: https://www.planalto.gov.br"
},
{
id: "sim01q71",
materia: "Conhecimentos Específicos",
assunto: "Responsabilidade socioambiental e economia de energia",
enunciado: "Em uma escola pública com elevado consumo de energia elétrica, a equipe de limpeza foi orientada a contribuir para a redução de gastos. Considerando a responsabilidade socioambiental no serviço público, a conduta que melhor se alinha à economicidade e à sustentabilidade é:",
a: "Manter equipamentos elétricos ligados durante todo o turno para evitar desgaste por acionamentos frequentes.",
b: "Utilizar iluminação natural sempre que possível e desligar equipamentos após o uso.",
c: "Centralizar o uso de equipamentos em apenas uma sala, independentemente da ventilação.",
d: "Substituir equipamentos elétricos por versões de maior potência.",
e: "Manter aparelhos em modo de espera para facilitar o reinício das atividades.",
correta: "b",
comentario: "A responsabilidade socioambiental envolve uso racional de energia, priorizando iluminação natural e desligamento de equipamentos quando não utilizados. Trata-se de prática alinhada à economicidade administrativa. Lei nº 12.305/2010 (Política Nacional de Resíduos Sólidos): https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/lei/l12305.htm"
},
{
id: "sim01q72",
materia: "Conhecimentos Específicos",
assunto: "Ética no serviço público",
enunciado: "Durante o expediente, um servidor da limpeza comenta informações internas sobre problemas administrativos da escola com pessoas externas à instituição. À luz da ética no serviço público, essa conduta deve ser considerada:",
a: "Adequada, pois o servidor tem liberdade de expressão irrestrita.",
b: "Aceitável se não houver prejuízo financeiro imediato.",
c: "Permitida quando a informação não estiver formalmente classificada.",
d: "Incompatível com o dever de discrição funcional.",
e: "Regular, desde que feita fora do horário de trabalho.",
correta: "d",
comentario: "O servidor público deve manter discrição quanto a informações internas, preservando a imagem institucional e o interesse público. O dever ético vai além da classificação formal da informação. Código de Ética do Servidor Público Federal: https://www.planalto.gov.br/ccivil_03/decreto/d1171.htm"
},
{
id: "sim01q73",
materia: "Conhecimentos Específicos",
assunto: "Prevenção de doenças transmissíveis",
enunciado: "Em período de aumento de casos de doenças respiratórias na comunidade escolar, o agente de limpeza deve adotar procedimentos que reduzam a possibilidade de transmissão indireta. A medida mais eficaz nesse contexto é:",
a: "Intensificar a higienização de superfícies de contato frequente.",
b: "Reduzir a frequência de limpeza para evitar dispersão de partículas.",
c: "Priorizar apenas a limpeza visual dos ambientes.",
d: "Realizar limpeza somente ao final do expediente.",
e: "Concentrar a desinfecção em áreas administrativas.",
correta: "a",
comentario: "Superfícies de contato frequente (maçanetas, corrimãos, mesas) são potenciais vetores de transmissão indireta. A higienização reforçada reduz riscos epidemiológicos. Manual da ANVISA sobre higienização de ambientes: https://www.gov.br/anvisa"
},
{
id: "sim01q74",
materia: "Conhecimentos Específicos",
assunto: "Pequenas tarefas de manutenção",
enunciado: "Ao identificar uma torneira com vazamento contínuo no sanitário escolar, o agente de limpeza deve agir considerando a preservação do patrimônio público e a economicidade. A conduta mais adequada é:",
a: "Ignorar o problema e comunicar apenas no fim do mês.",
b: "Interromper o uso do sanitário sem registro formal.",
c: "Tentar desmontar completamente a tubulação.",
d: "Comunicar imediatamente ao setor responsável e registrar a ocorrência.",
e: "Aguardar reclamação formal da direção.",
correta: "d",
comentario: "A preservação do patrimônio exige comunicação imediata e registro da ocorrência para providências técnicas. Vazamentos geram desperdício de água e danos estruturais. Lei nº 8.429/1992 (Improbidade Administrativa): https://www.planalto.gov.br/ccivil_03/leis/l8429.htm"
},
{
id: "sim01q75",
materia: "Conhecimentos Específicos",
assunto: "Segregação de resíduos",
enunciado: "Em ambiente escolar que realiza coleta seletiva, o descarte incorreto de resíduos pode comprometer o processo de reciclagem. Considerando a classificação usual, papéis contaminados com resíduos orgânicos devem ser:",
a: "Encaminhados para reciclagem comum.",
b: "Misturados ao plástico reciclável.",
c: "Descartados como rejeitos não recicláveis.",
d: "Armazenados junto ao vidro.",
e: "Encaminhados ao metal.",
correta: "c",
comentario: "Papéis contaminados perdem viabilidade de reciclagem e devem ser classificados como rejeitos. A segregação correta é essencial para o sucesso da coleta seletiva. Política Nacional de Resíduos Sólidos: https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/lei/l12305.htm"
},
{
id: "sim01q76",
materia: "Conhecimentos Específicos",
assunto: "Uso de EPIs",
enunciado: "Durante a aplicação de desinfetantes concentrados em sanitários, o agente deve utilizar EPIs adequados para prevenir riscos químicos. A combinação mais adequada para essa atividade é:",
a: "Luvas impermeáveis e proteção ocular.",
b: "Máscara de tecido e avental comum.",
c: "Sapato social e uniforme padrão.",
d: "Luvas de algodão e boné.",
e: "Óculos escuros e luvas térmicas.",
correta: "a",
comentario: "Produtos químicos concentrados exigem proteção das mãos e dos olhos para evitar irritações ou queimaduras. A NR-6 trata do uso adequado de EPIs. Norma Regulamentadora nº 6: https://www.gov.br/trabalho-e-emprego"
},
{
id: "sim01q77",
materia: "Conhecimentos Específicos",
assunto: "Organização de espaços escolares",
enunciado: "Após evento escolar no pátio, o agente de limpeza deve reorganizar o espaço considerando segurança e funcionalidade. A ação que melhor atende a esses critérios é:",
a: "Empilhar cadeiras próximas às saídas de emergência.",
b: "Reposicionar mobiliário conforme layout original e manter rotas desobstruídas.",
c: "Armazenar mesas no corredor principal.",
d: "Concentrar materiais no centro do ambiente.",
e: "Deixar reorganização para o turno seguinte.",
correta: "b",
comentario: "A organização deve preservar rotas de fuga e manter a disposição funcional do ambiente. Saídas de emergência precisam permanecer livres. NR-23 (Proteção Contra Incêndios): https://www.gov.br/trabalho-e-emprego"
},
{
id: "sim01q78",
materia: "Conhecimentos Específicos",
assunto: "Saúde pública em ambiente escolar",
enunciado: "A presença de água parada em áreas externas da escola pode representar risco à saúde coletiva. A conduta correta do agente de limpeza é:",
a: "Desconsiderar o acúmulo se estiver fora da área interna.",
b: "Cobrir a área com resíduos secos.",
c: "Comunicar e eliminar focos que possam favorecer proliferação de vetores.",
d: "Aguardar ação exclusiva da vigilância sanitária.",
e: "Aplicar produto químico sem orientação técnica.",
correta: "c",
comentario: "Água parada favorece proliferação de vetores como o Aedes aegypti. A eliminação de focos e comunicação são medidas preventivas essenciais. Ministério da Saúde: https://www.gov.br/saude"
},
{
id: "sim01q79",
materia: "Conhecimentos Específicos",
assunto: "Atendimento ao público",
enunciado: "Durante o atendimento a um responsável que solicita informação sobre localização de setor escolar, o agente de limpeza deve agir conforme princípios de urbanidade e eficiência. A postura adequada é:",
a: "Encaminhar o responsável sem fornecer orientação.",
b: "Responder de forma breve e imprecisa.",
c: "Ignorar por não ser sua função principal.",
d: "Prestar informação clara e, se necessário, indicar o setor correto.",
e: "Solicitar que o responsável aguarde outro servidor.",
correta: "d",
comentario: "O atendimento cortês e eficiente integra o dever funcional do servidor público, contribuindo para a imagem institucional. Princípios do art. 37 da Constituição Federal: https://www.planalto.gov.br/ccivil_03/constituicao/constituicao.htm"
},
{
id: "sim01q80",
materia: "Conhecimentos Específicos",
assunto: "Trabalho em equipe no ambiente escolar",
enunciado: "Em situação de grande demanda após atividade coletiva, a atuação coordenada entre agentes de limpeza é fundamental. A prática que demonstra efetivo trabalho em equipe é:",
a: "Dividir tarefas conforme planejamento prévio e comunicar ajustes necessários.",
b: "Executar tarefas isoladamente para ganhar autonomia.",
c: "Alterar funções sem informar colegas.",
d: "Priorizar atividades de interesse pessoal.",
e: "Aguardar orientação formal antes de qualquer ação.",
correta: "a",
comentario: "O trabalho em equipe exige planejamento, comunicação e cooperação entre os membros. A coordenação aumenta eficiência e reduz retrabalho. Fundamentos de gestão pública colaborativa: https://www.gov.br"
}
];